# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "CropSpec",
]

@typing.final
class CropSpec:
    r"""
    Parameters for the ``Crop`` transformer.
    
    The ``regions`` are pre-resolved clip regions in ops-local space,
    computed by Python from stock geometries + workpiece transform.
    """
    @property
    def tolerance(self) -> builtins.float:
        r"""
        Approximation tolerance for primitive refitting.
        """
    @property
    def offset(self) -> builtins.float:
        r"""
        Offset (mm) that was applied when growing the stock geometry;
        kept for traceability but not used by the dispatch.
        """
    @property
    def regions(self) -> builtins.list[builtins.list[tuple[builtins.float, builtins.float]]]:
        r"""
        Pre-resolved clip regions, each a polygon of ``(x, y)`` vertices.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, tolerance: builtins.float, offset: builtins.float, regions: typing.Sequence[typing.Sequence[tuple[builtins.float, builtins.float]]]) -> CropSpec: ...

