# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

from raygeo import ops
__all__ = [
    "polyline_to_ops",
]

def polyline_to_ops(points: list[tuple[float, float, float]], move_first: bool = True) -> ops.Ops:
    r"""
    Convert a 3-D polyline into an Ops command sequence.
    
    When *move_first* is ``True`` the first point is emitted as a
    MoveTo and subsequent points as LineTo.  When *move_first* is
    ``False`` every point is emitted as a LineTo (useful for
    appending a polyline to an in-progress cut).
    
    :param points: List of ``(x, y, z)`` tuples.
    :param move_first: Whether to emit the first point as a MoveTo.
    :returns: An :class:`~raygeo.ops.Ops` container.
    :complexity: O(n) where n = number of points
    """

