# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import raygeo
__all__ = [
    "generate_ramp",
]

def generate_ramp(part: raygeo.ops.part.Part, start: tuple[float, float], end: tuple[float, float], z_start: float, z_end: float, max_ramp_angle_deg: float = 45, style: str = 'zigzag', lateral_amplitude: float = 2, state: raygeo.ops.state.State | None = None) -> raygeo.ops.assembly.result.AssemblyResult:
    r"""
    Generate a ramp entry path.
    
    Produces a ramp (linear or zigzag) from *start* to *end* while
    descending from *z_start* to *z_end*.
    
    :param start: ``(x, y)`` start point.
    :param end: ``(x, y)`` end point.
    :param z_start: Starting Z height.
    :param z_end: Ending (target) Z depth.
    :param max_ramp_angle_deg: Maximum ramp angle in degrees (default 45).
    :param style: ``"linear"`` or ``"zigzag"`` (default ``"zigzag"``).
    :param lateral_amplitude: Lateral oscillation amplitude for zigzag (default 2.0).
    :param state: Optional machine state to apply before the path.
    :returns: An :class:`AssemblyResult` with the ramp path.
    """

