# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "LeadInOutSpec",
]

@typing.final
class LeadInOutSpec:
    r"""
    Parameters for the ``LeadInOut`` transformer.
    """
    @property
    def lead_in_mm(self) -> builtins.float:
        r"""
        Lead-in distance in millimeters.
        """
    @property
    def lead_out_mm(self) -> builtins.float:
        r"""
        Lead-out distance in millimeters.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, lead_in_mm: builtins.float, lead_out_mm: builtins.float) -> LeadInOutSpec: ...

