# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import collections.abc
import raygeo
__all__ = [
    "adaptive_clearing",
]

def adaptive_clearing(cleared: raygeo.ops.area.ClearedArea, pocket_boundary: collections.abc.Sequence[tuple[float, float]], islands: collections.abc.Sequence[collections.abc.Sequence[tuple[float, float]]] = [], radius: float = 3, advance: float = 1.5, cut_z: float = -5, safe_z: float = 2, step_length: float = 0.6, max_deflection_deg: float = 30, travel_smoothing: int = 50, wall_margin: float = 0, area_tolerance: float = 1, cut_feed_rate: int = 1200, travel_rapid_rate: int = 8000, cut_power: float = 1, start_pos: tuple[float, float] | None = None, start_heading: float | None = None, expansion_batch_size: int = 1, profile: bool = False) -> raygeo.ops.Ops:
    r"""
    Run forward-stepping adaptive clearing.
    
    Starting from the pre-populated *cleared* area, uses a
    constant-engagement stepping solver to generate a continuous
    spiral toolpath from the seed clearing to the pocket wall.
    
    The caller is responsible for populating *cleared* with entry
    polygons (e.g. from ``adaptive_entry``) and prepending the
    entry Ops to the result.
    
    :param cleared: ``ClearedArea`` instance (mutated in place).
    :param pocket_boundary: Outer boundary of the pocket.
    :param islands: List of island (hole) polygons (default []).
    :param radius: Tool radius in mm (default 3.0).
    :param advance: Forward advance per step (default 1.5).
    :param cut_z: Cutting Z height (default -5.0).
    :param safe_z: Retract Z height for travel (default 2.0).
    :param step_length: Forward distance per solver step (default 0.6).
    :param max_deflection_deg: Maximum steering deflection per step
                               in degrees (default 30).
    :param travel_smoothing: Reserved (default 50).
    :param wall_margin: Extra clearance between tool and boundary (default 0.0).
    :param area_tolerance: Stop when remaining uncut area drops below
                           this threshold (default 1.0).
    :param cut_feed_rate: Feed rate for cutting moves (default 1200).
    :param travel_rapid_rate: Rapid rate for travel moves (default 8000).
    :param cut_power: Laser power for cutting moves (0.0-1.0, default 1.0).
    :param start_pos: Initial tool position (x, y).  When None,
                      auto-detected from the cleared-area frontier.
    :param start_heading: Initial tool heading in radians.  When None,
                          auto-detected as the CCW tangent at start_pos.
    :param expansion_batch_size: Batch cleared-area expansions every
                                 N steps (default 1).  Larger values
                                 improve performance but may slightly
                                 reduce path quality.
    :param profile: Print a profiling report to stdout (default False).
    :returns: Ops with cutting commands (entry not included).
    """

