# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import collections.abc
import raygeo
from . import resume
from . import routing
from . import tool
__all__ = [
    "ResumePointNotFoundError",
    "RoutingError",
    "adaptive_clearing",
    "resume",
    "routing",
    "target_area_per_distance",
    "tool",
]

class ResumePointNotFoundError(builtins.RuntimeError):
    r"""
    Raised when all resume strategies fail to find an engagement point.
    """
    ...

class RoutingError(builtins.RuntimeError):
    r"""
    Raised when all route strategies fail to find a path.
    """
    ...

def adaptive_clearing(cleared: raygeo.ops.cut.cleared_area.ClearedArea, pocket_boundary: collections.abc.Sequence[tuple[float, float]], islands: collections.abc.Sequence[collections.abc.Sequence[tuple[float, float]]] = [], radius: float = 3, advance: float = 1.5, cut_z: float = -5, safe_z: float = 2, step_length: float = 0.6, max_deflection_deg: float = 30, wall_margin: float = 0, area_tolerance: float = 1, cut_feed_rate: int = 1200, cut_power: float = 1, start_pos: tuple[float, float] | None = None, start_heading: float | None = None, expansion_batch_size: int = 20, profile: bool = False, cut_direction: str = 'ccw', trace_path: str | None = None) -> raygeo.ops.assembly.result.AssemblyResult:
    r"""
    Run forward-stepping adaptive clearing.
    
    Starting from the pre-populated *cleared* area, uses a
    constant-engagement stepping solver to generate a continuous
    spiral toolpath from the seed clearing to the pocket wall.
    
    The caller is responsible for populating *cleared* with entry
    polygons (e.g. from ``adaptive_entry``) and prepending the
    entry Ops to the result.
    
    :param cleared: ``ClearedArea`` instance (mutated in place).
    :param pocket_boundary: Outer boundary of the pocket.
    :param islands: List of island (hole) polygons (default []).
    :param radius: Tool radius in mm (default 3.0).
    :param advance: Forward advance per step (default 1.5).
    :param cut_z: Cutting Z height (default -5.0).
    :param safe_z: Retract Z height for travel (default 2.0).
    :param step_length: Forward distance per solver step (default 0.6).
    :param max_deflection_deg: Maximum steering deflection per step
                               in degrees (default 30).
    :param wall_margin: Extra clearance between tool and boundary (default 0.0).
    :param area_tolerance: Stop when remaining uncut area drops below
                           this threshold (default 1.0).
    :param cut_feed_rate: Feed rate for cutting moves (default 1200).
    :param cut_power: Laser power for cutting moves (0.0-1.0, default 1.0).
    :param start_pos: Initial tool position (x, y).  When None,
                      auto-detected from the cleared-area frontier.
    :param start_heading: Initial tool heading in radians.  When None,
                          auto-detected as the CCW tangent at start_pos.
    :param expansion_batch_size: Batch cleared-area expansions every
                                 N steps (default 20).  Larger values
                                 improve performance but may slightly
                                 reduce path quality.
    :param profile: Print a profiling report to stdout (default False).
    :param cut_direction: Rotational direction of all cutting moves.
                          ``"cw"`` or ``"ccw"`` (default ``"ccw"``).
    :param trace_path: When set, write a per-step binary trace file for
                       the Python inspector (debug builds only).
    :returns: Ops with cutting commands (entry not included).
    """

def target_area_per_distance(radius: builtins.float, advance: builtins.float, step_length: builtins.float) -> builtins.float:
    r"""
    Target cut-area per unit distance for the engagement solver.
    
    :param radius: Tool radius in mm.
    :param advance: Step-over distance in mm.
    :param step_length: Forward step length in mm.
    :returns: Target area per distance (mm).
    """

