# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Overcut operations for closed contours.

Extends closed contours past their start point to ensure complete
cuts through the material, particularly useful in laser cutting
where the laser may not fully penetrate at the start/end point.
"""

__all__ = [
    "apply_overcut",
]

def apply_overcut(geometry: Geometry, overcut: float) -> Geometry:
    r"""
    Extend a closed contour past its start point.
    
    When laser-cutting closed contours, the laser slows down at
    corners and may not cut through completely. This function
    extends the path by ``overcut`` distance past the start point
    to ensure a clean cut.
    
    If the geometry is not closed, empty, or overcut is <= 0, the
    geometry is returned unchanged.
    
    :param geometry: The input geometry (must be closed).
    :param overcut: Distance to extend past the start point.
    :returns: A new geometry with the overcut applied.
    """

