# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Plain-data closed-manifold triangle meshes for solid interchange.
"""

import builtins
import typing
__all__ = [
    "SolidMesh",
]

@typing.final
class SolidMesh:
    r"""
    A closed-manifold triangle mesh in millimetres.
    
    The interchange format for solid geometry: f64 positions plus
    triangle indices and nothing else.
    """
    @property
    def positions(self) -> builtins.list[tuple[builtins.float, builtins.float, builtins.float]]:
        r"""
        Vertex positions (world mm).
        """
    @property
    def triangles(self) -> builtins.list[tuple[builtins.int, builtins.int, builtins.int]]:
        r"""
        Triangles as indices into ``positions``.
        """
    def __new__(cls, positions: typing.Sequence[tuple[builtins.float, builtins.float, builtins.float]], triangles: typing.Sequence[tuple[builtins.int, builtins.int, builtins.int]]) -> SolidMesh: ...
    def __len__(self) -> builtins.int: ...
    def __repr__(self) -> builtins.str: ...

