# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Matrix math utilities for geometric transformations.

Provides matrix multiplication for 4x4 affine transformation matrices,
which are used by Geometry.transform() and Ops.transform() to apply
translation, rotation, scaling, and shearing to paths.
"""

__all__ = [
    "mat4_mul",
]

def mat4_mul(a: Sequence[Sequence[float]], b: Sequence[Sequence[float]]) -> list[list[float]]:
    r"""
    Multiply two 4x4 matrices.
    
    :param a: First 4x4 matrix.
    :param b: Second 4x4 matrix.
    :returns: Resulting 4x4 matrix.
    """

