# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Geometric algorithms for path processing.

This module provides algorithms that operate on geometry paths and point
sequences. It covers several categories of geometric processing:

Clipping — intersect and clip line segments against rectangles and
polygon regions. Also includes coordinate conversion between floating
point and Clipper's integer grid system for boolean-accuracy clipping.

Fitting — reconstruct curves (arcs, lines, beziers) from unordered
point sequences. Includes recursive primitive fitting, circle fitting,
polyline linearization, and deviation analysis to evaluate fit quality.

Minkowski sums — compute Minkowski sums, convolutions, and no-fit
polygons for 2D toolpath generation, nesting, and packing algorithms.

Simplification — reduce the number of points in a polyline while
preserving shape within a tolerance (Ramer-Douglas-Peucker).

Smoothing — apply Gaussian kernel smoothing to polylines with
configurable corner-angle thresholds to preserve sharp features.
"""

from . import analysis
from . import clipping
from . import cylindrical
from . import fitting
from . import hull
from . import interp
from . import minkowski
from . import overcut
from . import simplify
from . import smooth
__all__ = [
    "analysis",
    "clipping",
    "cylindrical",
    "fitting",
    "hull",
    "interp",
    "minkowski",
    "overcut",
    "simplify",
    "smooth",
]

