# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Geometric algorithms for path processing.

This module provides algorithms that operate on geometry paths and point
sequences. It covers several categories of geometric processing:

Clipping — intersect and clip line segments against rectangles and
polygon regions. Also includes coordinate conversion between floating
point and Clipper's integer grid system for boolean-accuracy clipping.

Fitting — reconstruct curves (arcs, lines, beziers) from unordered
point sequences. Includes recursive primitive fitting, circle fitting,
polyline linearization, and deviation analysis to evaluate fit quality.

Minkowski sums — compute Minkowski sums, convolutions, and no-fit
polygons for 2D toolpath generation, nesting, and packing algorithms.

Nesting — 2D packing algorithms for sheet/plate layout (NFP, IFP,
placement, gravity, genetic optimization).

Simplification — reduce the number of points in a polyline while
preserving shape within a tolerance (Ramer-Douglas-Peucker).

Smoothing — apply Gaussian kernel smoothing to polylines with
configurable corner-angle thresholds to preserve sharp features.
"""

from . import analysis
from . import cleared_area
from . import clipping
from . import cylindrical
from . import fitting
from . import helix
from . import hsm
from . import hull
from . import interp
from . import intersect
from . import medial_axis
from . import minkowski2d
from . import nest2d
from . import offset
from . import overcut
from . import polylabel
from . import ramp
from . import simplify
from . import smooth
from . import spatial_grid2d
from . import spiral
from . import trochoid
__all__ = [
    "analysis",
    "cleared_area",
    "clipping",
    "cylindrical",
    "fitting",
    "helix",
    "hsm",
    "hull",
    "interp",
    "intersect",
    "medial_axis",
    "minkowski2d",
    "nest2d",
    "offset",
    "overcut",
    "polylabel",
    "ramp",
    "simplify",
    "smooth",
    "spatial_grid2d",
    "spiral",
    "trochoid",
]

