# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

__all__ = [
    "does_line_segment_intersect_circle",
    "does_line_segment_intersect_rect",
    "get_angle_at_vertex",
    "get_line_closest_point",
    "get_line_line_intersection",
    "get_line_segment_closest_point",
    "get_line_segment_intersection",
    "get_line_segment_polygon_intersections",
    "get_point_line_distance",
    "is_point_on_line_segment",
]

def does_line_segment_intersect_circle(p1: Point, p2: Point, circle_center: Point, circle_radius: float) -> bool:
    r"""
    Check if a line segment intersects a circle.
    
    :param p1: Start of the line segment.
    :param p2: End of the line segment.
    :param circle_center: Circle center (x, y).
    :param circle_radius: Circle radius.
    :returns: True if the segment intersects the circle.
    """

def does_line_segment_intersect_rect(p1: Point, p2: Point, rect: Rect) -> bool:
    r"""
    Check if a line segment intersects a rectangle.
    
    :param p1: Start of the line segment.
    :param p2: End of the line segment.
    :param rect: Rectangle (x_min, y_min, x_max, y_max).
    :returns: True if the segment intersects the rectangle.
    """

def get_angle_at_vertex(p0: Point, p1: Point, p2: Point) -> float:
    r"""
    Get the angle at a vertex between three points.
    
    :param p0: First point.
    :param p1: Vertex point.
    :param p2: Third point.
    :returns: Angle in radians.
    """

def get_line_closest_point(line_p1: Point, line_p2: Point, x: float, y: float) -> Point:
    r"""
    Get the closest point on a line to a given point.
    
    :param line_p1: First point on the line.
    :param line_p2: Second point on the line.
    :param x: X coordinate of target point.
    :param y: Y coordinate of target point.
    :returns: Closest point (x, y) on the line.
    """

def get_line_line_intersection(p1: Point, p2: Point, p3: Point, p4: Point) -> Optional[Point]:
    r"""
    Get the intersection of two infinite lines.
    
    :param p1: First point on line 1.
    :param p2: Second point on line 1.
    :param p3: First point on line 2.
    :param p4: Second point on line 2.
    :returns: Intersection point (x, y) or None.
    """

def get_line_segment_closest_point(seg_p1: Point, seg_p2: Point, x: float, y: float) -> tuple[float, Point, float]:
    r"""
    Get closest point on a line segment to a point.
    
    :param seg_p1: Start of the line segment.
    :param seg_p2: End of the line segment.
    :param x: X coordinate of target point.
    :param y: Y coordinate of target point.
    :returns: Tuple of (parameter, closest_point, distance).
    """

def get_line_segment_intersection(p1: Point, p2: Point, p3: Point, p4: Point) -> Optional[Point]:
    r"""
    Get the intersection of two line segments.
    
    :param p1: Start of segment 1.
    :param p2: End of segment 1.
    :param p3: Start of segment 2.
    :param p4: End of segment 2.
    :returns: Intersection point (x, y) or None.
    """

def get_line_segment_polygon_intersections(p1: Point, p2: Point, polygon: list[Polygon]) -> list[float]:
    r"""
    Get t-values of line segment-polygon intersections.
    
    :param p1: Start of the line segment.
    :param p2: End of the line segment.
    :param polygon: Polygon(s) to test against.
    :returns: List of t-values where the segment intersects.
    """

def get_point_line_distance(point: Point, line_p1: Point, line_p2: Point) -> float:
    r"""
    Get the distance from a point to a line.
    
    :param point: Point (x, y).
    :param line_p1: First point on the line.
    :param line_p2: Second point on the line.
    :returns: Perpendicular distance.
    """

def is_point_on_line_segment(point: Point, seg_p1: Point, seg_p2: Point) -> bool:
    r"""
    Check if a point is on a line segment.
    
    :param point: Point (x, y) to test.
    :param seg_p1: Start of the line segment.
    :param seg_p2: End of the line segment.
    :returns: True if the point lies on the segment.
    """

