# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

__all__ = [
    "midpoint",
]

def midpoint(p1: tuple[float, float, float], p2: tuple[float, float, float]) -> tuple[float, float, float]:
    r"""
    Get the midpoint between two 3D points.
    """

