[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "raygeo"
dynamic = ["version"]
description = "A 2D/3D geometry library for CAD/CAM applications."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Samuel Abels", email = "knipknap@gmail.com" }
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "numpy>=1.20.0"
]

[project.optional-dependencies]
test = [
    "matplotlib",
    "pycairo",
    "pytest",
    "pytest-mock",
    "streamlit",
]
visual = [
    "streamlit",
    "matplotlib",
]
docs = [
    "matplotlib",
    "mdformat",
    "mdformat-frontmatter",
    "mdformat-tables",
    "Pillow",
]

cli = [
    "matplotlib",
    "msgpack",
]

[project.scripts]
raygeo = "raygeo.cli.main:main"
raygeo-docs = "tools.cli:main"

[tool.maturin]
module-name = "raygeo"
python-source = "python"

[tool.pyo3-stub-gen]
module-name = "raygeo"

[tool.pyright]
stubPath = "python"
reportMissingModuleSource = false
include = ["tests", "python"]

[tool.ruff]
line-length = 79
exclude = ["*.pyi"]

[tool.ruff.lint]
select = ["E", "F", "W", "I"]

[tool.ruff.lint.isort]
known-first-party = ["raygeo"]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "slow: marks tests as slow (deselect with '-k \"not slow\"')",
]
