[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "raygeo"
version = "0.1.0"
description = "A 2D/3D geometry library for CAD/CAM applications."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Samuel Abels", email = "knipknap@gmail.com" }
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "numpy>=1.20.0"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-mock",
]

[tool.maturin]
module-name = "raygeo"
features = ["pyo3/extension-module"]
include = ["raygeo-stubs/**/*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
