# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from raygeo.ops.transform import merge_scanlines
import typing
__all__ = [
    "OptimizeSpec",
]

@typing.final
class OptimizeSpec:
    r"""
    Parameters for the ``Optimize`` (travel optimization) transformer.
    """
    @property
    def allow_flip(self) -> builtins.bool:
        r"""
        Whether flipping subpaths is allowed.
        """
    @property
    def preserve_first(self) -> builtins.bool:
        r"""
        Keep the first workpiece in place.
        """
    @property
    def preserve_order(self) -> builtins.list[builtins.str]:
        r"""
        Workpiece UIDs whose order to preserve.
        """
    @property
    def merge_scanlines(self) -> typing.Optional[merge_scanlines.MergeScanlinesSpec]:
        r"""
        When set, acceleration-aware scanline merging runs before the
        travel optimization.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, allow_flip: builtins.bool, preserve_first: builtins.bool, preserve_order: typing.Sequence[builtins.str], merge_scanlines: typing.Optional[merge_scanlines.MergeScanlinesSpec] = None) -> OptimizeSpec: ...

