# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Command sequence (Ops) manipulation for laser cutter motion control.

Ops is a container of ordered commands (move, line, arc, bezier, state
changes like power/speed) that defines a complete laser engraving or
cutting job. It supports building sequences programmatically (move_to,
line_to, arc_to, etc.), transforming them (translate, rotate, scale,
transform with 4x4 matrices), clipping to rectangles or regions,
linearizing curves, estimating processing time, and serializing to
dict or numpy arrays for persistence.

The module also provides command-type enumerations (CommandType,
CommandCategory, SectionType), machine State tracking (power, speed,
air assist, frequency), and an Axis bitflag for multi-axis machines.
"""

import builtins
import raygeo
from raygeo import geo
import typing
from . import axis
from . import raster
from . import state
from . import types
__all__ = [
    "CommandInfo",
    "Ops",
    "OpsSection",
    "OpsSectionRange",
    "axis",
    "raster",
    "state",
    "types",
]

@typing.final
class CommandInfo:
    r"""
    Detailed information about a single command in an Ops sequence.
    
    Returned by :meth:`Ops.inspect` and provides the full set of
    parameters for any command type in a structured form.
    """
    @property
    def type_(self) -> types.CommandType: ...
    @property
    def end(self) -> typing.Optional[tuple[float, float, float]]: ...
    @property
    def extra_axes(self) -> typing.Optional[dict]: ...
    @property
    def state(self) -> typing.Optional[state.State]: ...
    @property
    def center_offset(self) -> typing.Optional[tuple[float, float]]: ...
    @property
    def clockwise(self) -> typing.Optional[builtins.bool]: ...
    @property
    def control1(self) -> typing.Optional[tuple[float, float, float]]: ...
    @property
    def control2(self) -> typing.Optional[tuple[float, float, float]]: ...
    @property
    def control(self) -> typing.Optional[tuple[float, float, float]]: ...
    @property
    def power_values(self) -> typing.Optional[bytes]: ...
    @property
    def power(self) -> typing.Optional[builtins.float]: ...
    @property
    def speed(self) -> typing.Optional[builtins.int]: ...
    @property
    def frequency(self) -> typing.Optional[builtins.int]: ...
    @property
    def pulse_width(self) -> typing.Optional[builtins.float]: ...
    @property
    def laser_uid(self) -> typing.Optional[builtins.str]: ...
    @property
    def duration_ms(self) -> typing.Optional[builtins.float]: ...
    @property
    def layer_uid(self) -> typing.Optional[builtins.str]: ...
    @property
    def workpiece_uid(self) -> typing.Optional[builtins.str]: ...
    @property
    def section_type(self) -> typing.Optional[builtins.str]: ...
    def __eq__(self, other: typing.Any) -> builtins.bool: ...

@typing.final
class Ops:
    r"""
    A sequence of laser cutting operations (commands).
    
    ``Ops`` is a container of ordered commands that define a complete
    laser engraving or cutting job. It supports building command sequences
    programmatically, transforming them, clipping, serializing, and more.
    
    Use the builder methods (``move_to``, ``line_to``, ``arc_to``, etc.)
    to construct a sequence, or load from geometry/dict/numpy arrays.
    """
    @property
    def scanline_count(self) -> builtins.int:
        r"""
        Return the number of scanline commands in the sequence.
        """
    @property
    def last_move_to(self) -> builtins.tuple[float, float, float]:
        r"""
        The last ``(x, y, z)`` endpoint from a MoveTo command.
        """
    @last_move_to.setter
    def last_move_to(self, value: builtins.tuple[float, float, float]) -> None: ...
    def transform(self, matrix: geo.types.TransformMatrix) -> None:
        r"""
        Apply a 4x4 affine transformation matrix to all geometry.
        
        See ``geo.types.TransformMatrix`` for the matrix layout.
        
        :param matrix: A 4x4 affine transformation matrix.
        """
    def __new__(cls) -> Ops:
        r"""
        Create a new, empty Ops sequence.
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of commands.
        """
    def __add__(self, other: Ops) -> Ops:
        r"""
        Concatenate two Ops sequences (``ops1 + ops2``).
        """
    def __mul__(self, count: builtins.int) -> Ops:
        r"""
        Repeat the ops sequence *count* times (``ops * n``).
        """
    def is_empty(self) -> builtins.bool:
        r"""
        Check if the ops sequence is empty.
        """
    def len(self) -> builtins.int:
        r"""
        Return the number of commands.
        """
    def command_type(self, idx: builtins.int) -> types.CommandType:
        r"""
        Get the :class:`CommandType` at the given index.
        
        :param idx: Command index (negative = from end).
        :returns: The :class:`CommandType` of the command.
        """
    def category(self, idx: builtins.int) -> types.CommandCategory:
        r"""
        Get the :class:`CommandCategory` at the given index.
        
        :param idx: Command index (negative = from end).
        :returns: The category (MOVING, STATE, or MARKER).
        """
    def is_travel(self, idx: builtins.int) -> builtins.bool:
        r"""
        Check whether the command at *idx* is a travel (non-cutting) move.
        
        :param idx: Command index.
        :returns: True if the command is a travel move.
        """
    def is_cutting(self, idx: builtins.int) -> builtins.bool:
        r"""
        Check whether the command at *idx* is a cutting move.
        
        :param idx: Command index.
        :returns: True if the command is a cutting move.
        """
    def is_state(self, idx: builtins.int) -> builtins.bool:
        r"""
        Check whether the command at *idx* is a state command.
        
        :param idx: Command index.
        :returns: True if the command modifies machine state.
        """
    def is_marker(self, idx: builtins.int) -> builtins.bool:
        r"""
        Check whether the command at *idx* is a marker command.
        
        :param idx: Command index.
        :returns: True if the command is a structural marker (JobStart, LayerStart, etc.).
        """
    def is_scanline(self, idx: builtins.int) -> builtins.bool:
        r"""
        Check whether the command at *idx* is a scanline command.
        
        :param idx: Command index.
        :returns: True if the command is a ScanLine power command.
        """
    def indices_of(self, ct: types.CommandType) -> builtins.list[builtins.int]:
        r"""
        Return all indices where the command type matches *ct*.
        
        :param ct: The :class:`CommandType` to search for.
        :returns: List of matching command indices.
        """
    def distance_at(self, idx: builtins.int, last_point: typing.Optional[tuple[builtins.float, builtins.float, builtins.float]] = None) -> builtins.float:
        r"""
        Compute the distance traveled up to command *idx*.
        
        :param idx: Command index.
        :param last_point: Optional starting point override.
        :returns: Cumulative distance.
        """
    def distance(self) -> builtins.float:
        r"""
        Compute the total distance of all commands.
        """
    def cut_distance(self) -> builtins.float:
        r"""
        Compute the total cutting distance (excluding travel moves).
        """
    def endpoint(self, idx: builtins.int) -> builtins.tuple[float, float, float]:
        r"""
        Get the endpoint coordinates of a moving command.
        
        :param idx: Command index (negative = from end).
        :returns: ``(x, y, z)`` tuple.
        """
    def arc_params(self, idx: builtins.int) -> tuple[builtins.float, builtins.float, builtins.bool]:
        r"""
        Get the arc parameters (center offset i, j, and clockwise flag).
        
        :param idx: Command index.
        :returns: ``(i, j, clockwise)`` tuple.
        :raises TypeError: If the command is not an ArcTo.
        """
    def bezier_params(self, idx: builtins.int) -> tuple[tuple[float, float, float], tuple[float, float, float]]:
        r"""
        Get the cubic bezier control points.
        
        :param idx: Command index.
        :returns: ``((c1x, c1y, c1z), (c2x, c2y, c2z))`` control points.
        :raises TypeError: If the command is not a BezierTo.
        """
    def quadratic_bezier_params(self, idx: builtins.int) -> builtins.tuple[float, float, float]:
        r"""
        Get the quadratic bezier control point.
        
        :param idx: Command index.
        :returns: ``(cx, cy, cz)`` control point.
        :raises TypeError: If the command is not a QuadraticBezierTo.
        """
    def scanline_data(self, idx: builtins.int) -> bytes:
        r"""
        Get the raw scanline power data for a scanline command.
        
        :param idx: Command index.
        :returns: Raw bytes of scanline power data.
        """
    def dwell_duration(self, idx: builtins.int) -> builtins.float:
        r"""
        Get the duration (milliseconds) of a Dwell command.
        
        :param idx: Command index.
        :returns: Duration in milliseconds.
        :raises TypeError: If the command is not a Dwell.
        """
    def power(self, idx: builtins.int) -> builtins.float:
        r"""
        Get the power level of a SetPower command.
        
        :param idx: Command index.
        :returns: Power level (0.0–1.0 typically).
        :raises TypeError: If the command is not a SetPower.
        """
    def speed(self, idx: builtins.int) -> builtins.int:
        r"""
        Get the speed value from a SetCutSpeed or SetTravelSpeed command.
        
        :param idx: Command index.
        :returns: Speed in mm/s.
        :raises TypeError: If the command is not a speed command.
        """
    def frequency(self, idx: builtins.int) -> builtins.int:
        r"""
        Get the frequency of a SetFrequency command.
        
        :param idx: Command index.
        :returns: Frequency in Hz.
        :raises TypeError: If the command is not a SetFrequency.
        """
    def pulse_width(self, idx: builtins.int) -> builtins.float:
        r"""
        Get the pulse width of a SetPulseWidth command.
        
        :param idx: Command index.
        :returns: Pulse width in microseconds.
        :raises TypeError: If the command is not a SetPulseWidth.
        """
    def laser_uid(self, idx: builtins.int) -> builtins.str:
        r"""
        Get the laser UID from a SetLaser command.
        
        :param idx: Command index.
        :returns: The laser source identifier.
        :raises TypeError: If the command is not a SetLaser.
        """
    def layer_uid(self, idx: builtins.int) -> builtins.str:
        r"""
        Get the layer UID from a LayerStart or LayerEnd command.
        
        :param idx: Command index.
        :returns: The layer identifier.
        :raises TypeError: If the command is not a Layer command.
        """
    def workpiece_uid(self, idx: builtins.int) -> builtins.str:
        r"""
        Get the workpiece UID from a WorkpieceStart or WorkpieceEnd command.
        
        :param idx: Command index.
        :returns: The workpiece identifier.
        :raises TypeError: If the command is not a Workpiece command.
        """
    def section_params(self, idx: builtins.int) -> tuple[types.SectionType, typing.Optional[builtins.str]]:
        r"""
        Get the section type and optional workpiece UID from an OpsSection command.
        
        :param idx: Command index.
        :returns: ``(SectionType, Optional[workpiece_uid])``.
        :raises TypeError: If the command is not an OpsSectionStart or OpsSectionEnd.
        """
    def extra_axes(self, idx: builtins.int) -> typing.Optional[dict]:
        r"""
        Get the extra axes data for a moving command.
        
        :param idx: Command index.
        :returns: Dict mapping axis names to values, or None.
        """
    def state(self, idx: builtins.int) -> typing.Optional[state.State]:
        r"""
        Get the machine state stored on a command (if available).
        
        :param idx: Command index.
        :returns: The :class:`State` at that index, or None.
        """
    def move_to(self, x: builtins.float, y: builtins.float, z: builtins.float = 0.0, extra: typing.Optional[dict] = None) -> None:
        r"""
        Add a rapid (non-cutting) move to the given coordinates.
        
        :param x: X coordinate.
        :param y: Y coordinate.
        :param z: Z coordinate (default 0.0).
        :param extra: Optional dict of extra axis values.
        """
    def line_to(self, x: builtins.float, y: builtins.float, z: builtins.float = 0.0, extra: typing.Optional[dict] = None) -> None:
        r"""
        Add a cutting line to the given coordinates.
        
        :param x: X coordinate.
        :param y: Y coordinate.
        :param z: Z coordinate (default 0.0).
        :param extra: Optional dict of extra axis values.
        """
    def close_path(self) -> None:
        r"""
        Close the current sub-path by adding a line back to the start.
        """
    def arc_to(self, x: builtins.float, y: builtins.float, i: builtins.float, j: builtins.float, clockwise: builtins.bool = True, z: builtins.float = 0.0, extra: typing.Optional[dict] = None) -> None:
        r"""
        Add a circular arc to the given coordinates.
        
        :param x: End X coordinate.
        :param y: End Y coordinate.
        :param i: I offset from current point to arc center.
        :param j: J offset from current point to arc center.
        :param clockwise: Whether the arc is clockwise (default True).
        :param z: End Z coordinate (default 0.0).
        :param extra: Optional dict of extra axis values.
        """
    def bezier_to(self, control1: builtins.tuple[float, float, float], control2: builtins.tuple[float, float, float], end: builtins.tuple[float, float, float], extra: typing.Optional[dict] = None) -> None:
        r"""
        Add a cubic bezier curve to the given endpoint.
        
        :param control1: First control point ``(x, y, z)``.
        :param control2: Second control point ``(x, y, z)``.
        :param end: End point ``(x, y, z)``.
        :param extra: Optional dict of extra axis values.
        """
    def quadratic_bezier_to(self, control: builtins.tuple[float, float, float], end: builtins.tuple[float, float, float], extra: typing.Optional[dict] = None) -> None:
        r"""
        Add a quadratic bezier curve to the given endpoint.
        
        :param control: Control point ``(x, y, z)``.
        :param end: End point ``(x, y, z)``.
        :param extra: Optional dict of extra axis values.
        """
    def set_power(self, power: builtins.float) -> None:
        r"""
        Set the laser power for subsequent commands.
        
        :param power: Power level (0.0–1.0).
        """
    def set_cut_speed(self, speed: builtins.float) -> None:
        r"""
        Set the cutting speed for subsequent commands.
        
        :param speed: Cutting speed in units per second.
        """
    def set_travel_speed(self, speed: builtins.float) -> None:
        r"""
        Set the travel (rapid) speed for subsequent commands.
        
        :param speed: Travel speed in units per second.
        """
    def dwell(self, duration_ms: builtins.float) -> None:
        r"""
        Pause execution for a given duration.
        
        :param duration_ms: Dwell duration in milliseconds.
        """
    def enable_air_assist(self, enabled: builtins.bool = True) -> None:
        r"""
        Enable air assist for subsequent cutting.
        
        :param enabled: Whether to enable air assist (default True).
        """
    def set_laser(self, laser_uid: builtins.str) -> None:
        r"""
        Switch to a specific laser by UID.
        
        :param laser_uid: The laser identifier.
        """
    def set_frequency(self, frequency: builtins.int) -> None:
        r"""
        Set the laser pulse frequency.
        
        :param frequency: Frequency in Hz.
        """
    def set_pulse_width(self, pulse_width: builtins.float) -> None:
        r"""
        Set the laser pulse width.
        
        :param pulse_width: Pulse width in microseconds.
        """
    def scan_to(self, x: builtins.float, y: builtins.float, z: builtins.float = 0.0, power_values: typing.Optional[typing.Sequence[builtins.int]] = None, extra: typing.Optional[dict] = None) -> None:
        r"""
        Add a scan-line move with per-pixel power values.
        
        :param x: End X coordinate.
        :param y: End Y coordinate.
        :param z: End Z coordinate (default 0.0).
        :param power_values: Optional per-pixel 8-bit power values.
        :param extra: Optional dict of extra axis values.
        """
    def job_start(self) -> None:
        r"""
        Mark the start of a job.
        """
    def job_end(self) -> None:
        r"""
        Mark the end of a job.
        """
    def layer_start(self, layer_uid: builtins.str) -> None:
        r"""
        Mark the start of a layer.
        
        :param layer_uid: The layer identifier.
        """
    def layer_end(self, layer_uid: builtins.str) -> None:
        r"""
        Mark the end of a layer.
        
        :param layer_uid: The layer identifier.
        """
    def workpiece_start(self, workpiece_uid: builtins.str) -> None:
        r"""
        Mark the start of a workpiece.
        
        :param workpiece_uid: The workpiece identifier.
        """
    def workpiece_end(self, workpiece_uid: builtins.str) -> None:
        r"""
        Mark the end of a workpiece.
        
        :param workpiece_uid: The workpiece identifier.
        """
    def ops_section_start(self, section_type: types.SectionType, workpiece_uid: builtins.str) -> None:
        r"""
        Mark the start of an ops section.
        
        :param section_type: The type of section.
        :param workpiece_uid: The workpiece identifier.
        """
    def ops_section_end(self, section_type: types.SectionType) -> None:
        r"""
        Mark the end of an ops section.
        
        :param section_type: The type of section.
        """
    def copy(self) -> Ops:
        r"""
        Return a deep copy of this Ops sequence.
        """
    def __copy__(self) -> Ops:
        r"""
        Shallow copy (same as :meth:`copy` since Ops is immutable).
        """
    def __deepcopy__(self, _memo: typing.Any) -> Ops:
        r"""
        Deep copy (same as :meth:`copy` since Ops is immutable).
        """
    def copy_command_from(self, source: Ops, idx: builtins.int) -> None:
        r"""
        Copy a single command from another Ops sequence into this one.
        
        :param source: The source Ops sequence.
        :param idx: Index of the command to copy.
        """
    def transfer_command_from(self, source: Ops, idx: builtins.int) -> None:
        r"""
        Transfer (move) a single command from another Ops sequence into this one.
        
        :param source: The source Ops sequence.
        :param idx: Index of the command to transfer.
        """
    def extend(self, other: typing.Optional[Ops]) -> None:
        r"""
        Extend this Ops sequence with commands from another.
        
        :param other: The other Ops sequence (or None for no-op).
        """
    def clear(self) -> None:
        r"""
        Remove all commands from this Ops sequence.
        """
    def subpath_indices(self) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Return index ranges for each subpath.
        
        :returns: A list of index lists, one per subpath.
        """
    def split_into_subpaths(self) -> builtins.list[Ops]:
        r"""
        Split this Ops sequence into separate subpaths.
        
        :returns: A list of Ops sequences, one per subpath.
        """
    def flip_ops(self) -> Ops:
        r"""
        Reverse the order of subpaths.
        
        :returns: A new Ops with subpath order reversed.
        """
    def without_state(self) -> Ops:
        r"""
        Return a copy with all state commands removed.
        
        :returns: A new Ops containing only moving commands.
        """
    def state_at(self, idx: builtins.int) -> state.State:
        r"""
        Return the accumulated state at a given command index.
        
        :param idx: The command index.
        :returns: The state at that point.
        :raises IndexError: If the index is out of range.
        """
    def sub_ops(self, indices: typing.Sequence[builtins.int]) -> Ops:
        r"""
        Extract a subset of commands by index.
        
        :param indices: List of command indices to extract.
        :returns: A new Ops sequence containing only the specified commands.
        """
    def replace_all(self, source: Ops) -> None:
        r"""
        Replace all commands in this sequence with those from another.
        
        :param source: The source Ops sequence.
        """
    def replace_with(self, source: Ops) -> None:
        r"""
        Replace the internal buffer of this sequence with a copy from another.
        
        :param source: The source Ops sequence.
        """
    @classmethod
    def from_geometry(cls, geometry: geo.Geometry) -> Ops:
        r"""
        Create an Ops sequence from a Geometry.
        
        :param geometry: The geometry to convert.
        """
    def to_geometry(self) -> geo.Geometry:
        r"""
        Convert this Ops sequence back into a Geometry.
        
        :returns: A Geometry representing the same paths.
        """
    def preload_state(self) -> None:
        r"""
        Pre-compute and store the accumulated state at each moving command.
        """
    def set_state_on_moving(self, state: state.State) -> None:
        r"""
        Apply a state to all moving commands without an explicit state.
        
        :param state: The state to apply.
        """
    def set_state_at(self, idx: builtins.int, state: state.State) -> None:
        r"""
        Overwrite the state at a specific command index.
        
        :param idx: The command index.
        :param state: The new state.
        """
    def dump(self) -> None:
        r"""
        Print a human-readable dump of all commands.
        """
    def inspect(self, idx: builtins.int) -> CommandInfo:
        r"""
        Return detailed information about a single command.
        
        :param idx: The command index.
        :returns: A CommandInfo object with type, endpoint, state, axes, etc.
        """
    def translate(self, dx: builtins.float, dy: builtins.float, dz: builtins.float = 0.0) -> None:
        r"""
        Translate all moving commands by the given offset.
        
        :param dx: X offset.
        :param dy: Y offset.
        :param dz: Z offset (default 0.0).
        """
    def scale(self, sx: builtins.float, sy: builtins.float, sz: builtins.float = 1.0) -> None:
        r"""
        Scale all coordinates by the given factors.
        
        :param sx: X scale factor.
        :param sy: Y scale factor.
        :param sz: Z scale factor (default 1.0).
        """
    def rotate(self, angle_deg: builtins.float, cx: builtins.float, cy: builtins.float) -> None:
        r"""
        Rotate all coordinates around a pivot point.
        
        :param angle_deg: Rotation angle in degrees.
        :param cx: Pivot X coordinate.
        :param cy: Pivot Y coordinate.
        """
    def clip_rect(self, rect: tuple[builtins.float, builtins.float, builtins.float, builtins.float]) -> Ops:
        r"""
        Clip this sequence to a rectangle, keeping only commands inside.
        
        :param rect: ``(x_min, y_min, x_max, y_max)``.
        :returns: A new Ops sequence containing the clipped commands.
        """
    def subtract_regions(self, regions: typing.Sequence[typing.Sequence[tuple[float, float]]]) -> None:
        r"""
        Subtract polygonal regions from the cutting paths.
        
        :param regions: List of polygons, each being a list of ``(x, y)`` vertices.
        """
    def clip_to_regions(self, regions: typing.Sequence[typing.Sequence[tuple[builtins.float, builtins.float]]], tolerance: builtins.float = 0.3) -> None:
        r"""
        Clip paths to the given polygonal regions, keeping only what is inside.
        
        :param regions: List of polygons, each being a list of ``(x, y)`` vertices.
        :param tolerance: Approximation tolerance (default 0.3).
        """
    def clip_ops_to_regions(self, regions: typing.Sequence[typing.Sequence[tuple[float, float]]], tolerance: builtins.float = 0.3) -> None:
        r"""
        Clip paths using polygonal regions as boundaries; keeps what is inside.
        
        :param regions: List of polygons, each being a list of ``(x, y)`` vertices.
        :param tolerance: Approximation tolerance (default 0.3).
        """
    def clip_at(self, x: builtins.float, y: builtins.float, width: builtins.float) -> builtins.bool:
        r"""
        Clip at a single vertical swath, keeping commands that intersect the band.
        
        :param x: X coordinate of the left edge.
        :param y: Y coordinate (used to find the relevant segment).
        :param width: Width of the band.
        :returns: True if any commands were kept.
        """
    def translate_layers(self, default_offset: tuple[builtins.float, builtins.float, builtins.float], layer_offsets: typing.Optional[dict] = None) -> None:
        r"""
        Translate each layer by its own offset, with a default fallback.
        
        :param default_offset: The ``(x, y, z)`` offset for layers not listed in layer_offsets.
        :param layer_offsets: Optional dict mapping layer UIDs to ``(x, y, z)`` offsets.
        """
    def transform_layers(self, callback: typing.Any) -> None:
        r"""
        Transform each layer by calling a Python callback with the layer UID and ops.
        
        The callback receives ``(layer_uid: str, layer_ops: Ops)`` and should
        mutate the layer_ops in place.
        
        :param callback: A callable accepting ``(layer_uid, layer_ops)``.
        """
    def transform_moving(self, on_endpoint: typing.Any, on_aux_point: typing.Optional[typing.Any] = None) -> None:
        r"""
        Transform moving commands by calling Python callbacks on each endpoint and aux point.
        
        The ``on_endpoint`` callback receives ``(endpoint, extra_axes)`` and
        should mutate the endpoint list in-place. The optional ``on_aux_point``
        callback receives control points for curve commands.
        
        :param on_endpoint: Callable ``(endpoint, extra_axes) -> None``.
        :param on_aux_point: Optional callable ``(point,) -> None`` for curve control points.
        """
    def linearize(self, idx: builtins.int, start_point: builtins.tuple[float, float, float]) -> Ops:
        r"""
        Decompose a curved command into linear segments.
        
        :param idx: Index of the command to linearize.
        :param start_point: The ``(x, y, z)`` start point of the curve.
        :returns: A new Ops containing the linearized sub-commands.
        :raises TypeError: If the command at idx is not a curve or line type.
        """
    def linearize_all(self) -> None:
        r"""
        Replace all curved commands with linear approximations in-place.
        """
    def linearize_curves(self) -> None:
        r"""
        Replace only bezier and quadratic bezier curves with linear approximations.
        """
    def linearize_arcs(self) -> None:
        r"""
        Replace only arc commands with linear approximations.
        """
    def segment_indices(self) -> builtins.list[builtins.list[builtins.int]]:
        r"""
        Return index ranges for each contiguous cutting segment.
        
        :returns: A list of index lists, one per segment.
        """
    def group_by_state_continuity(self) -> builtins.list[Ops]:
        r"""
        Group contiguous commands with the same state into separate Ops sequences.
        
        :returns: A list of Ops sequences grouped by state continuity.
        """
    def sections(self) -> builtins.list[OpsSection]:
        r"""
        Return the logical sections of the ops.
        
        Sections are delimited by ``OpsSectionStart``/``OpsSectionEnd``
        markers and group commands into vector-outline and raster-fill
        portions.
        
        :returns: List of OpsSection objects.
        """
    def section_ranges(self) -> builtins.list[OpsSectionRange]:
        r"""
        Return the section ranges of the ops as index ranges.
        
        Similar to :meth:`sections` but returns contiguous
        index ranges instead of individual index lists.
        
        :returns: List of OpsSectionRange objects.
        """
    def rect(self, include_travel: builtins.bool = False) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float]:
        r"""
        Compute the bounding rectangle of all commands.
        
        :param include_travel: Whether to include travel moves (default False).
        :returns: ``(x_min, y_min, x_max, y_max)``.
        """
    def get_frame(self, power: typing.Optional[builtins.float] = None, speed: typing.Optional[builtins.float] = None) -> Ops:
        r"""
        Extract a frame (first and last endpoints) from the sequence.
        
        :param power: Optional power to set on the frame commands.
        :param speed: Optional speed to set on the frame commands.
        :returns: A new Ops containing only the frame endpoints.
        """
    def estimate_time(self, default_cut_speed: builtins.float = 1000.0, default_travel_speed: builtins.float = 3000.0, acceleration: builtins.float = 1000.0) -> builtins.float:
        r"""
        Estimate the total processing time for this sequence.
        
        :param default_cut_speed: Default cutting speed (default 1000.0).
        :param default_travel_speed: Default travel speed (default 3000.0).
        :param acceleration: Acceleration value (default 1000.0).
        :returns: Estimated time in seconds.
        """
    def estimate_command_times(self, default_cut_speed: builtins.float = 1000.0, default_travel_speed: builtins.float = 3000.0, acceleration: builtins.float = 1000.0) -> builtins.list[builtins.float]:
        r"""
        Estimate the time of each individual command in the sequence.
        
        Returns a list with one entry per command. Moving commands
        (MoveTo, LineTo, ArcTo, etc.) yield their estimated execution
        time in seconds. Non-moving commands (state changes, markers)
        yield 0.0.
        
        :param default_cut_speed: Default cutting speed (default 1000.0).
        :param default_travel_speed: Default travel speed (default 3000.0).
        :param acceleration: Acceleration value (default 1000.0).
        :returns: List of estimated times in seconds, one per command.
        """
    def to_dict(self) -> dict:
        r"""
        Serialize this Ops sequence to a dict suitable for JSON export.
        
        :returns: A Python dict representation.
        """
    @classmethod
    def from_dict(cls, data: dict) -> Ops:
        r"""
        Create an Ops sequence from a dictionary.
        
        :param data: Dictionary as produced by to_dict.
        """
    def to_numpy_arrays(self) -> dict:
        r"""
        Serialize this Ops sequence to numpy arrays.
        
        :returns: A Python dict of numpy arrays.
        """
    @classmethod
    def from_numpy_arrays(cls, arrays: dict) -> Ops:
        r"""
        Create an Ops sequence from numpy arrays.
        
        :param arrays: Dictionary as produced by to_numpy_arrays.
        """
    def apply_tab_gaps(self, clips: typing.Sequence[tuple[builtins.float, builtins.float, builtins.float]]) -> None:
        r"""
        Apply holding tabs as gaps in the toolpath.
        
        For each clip point, the closest subpath is found and a gap of
        the specified width is cut at the nearest point on the path.
        Only ``VECTOR_OUTLINE`` sections are modified.
        
        :param clips: List of ``(x, y, width)`` tuples defining tab positions.
        """
    def apply_tab_power(self, clips: typing.Sequence[tuple[builtins.float, builtins.float, builtins.float]], tab_power: builtins.float, original_power: builtins.float) -> None:
        r"""
        Apply holding tabs by reducing laser power in tab regions.
        
        Instead of cutting a gap, the laser power is lowered in the tab
        area so the material stays connected but weaker. Only
        ``VECTOR_OUTLINE`` sections are modified.
        
        :param clips: List of ``(x, y, width)`` tuples defining tab positions.
        :param tab_power: Power level inside tab regions (0.0–1.0).
        :param original_power: Normal cutting power to restore after the tab.
        """
    def merge_overlapping_lines(self, tolerance: builtins.float) -> None:
        r"""
        Merge overlapping line segments across all paths.
        
        Detects line segments that are collinear and overlapping and
        replaces the covered sub-segments with travel moves to avoid
        cutting the same line twice.
        
        :param tolerance: Maximum distance for considering lines collinear.
        """
    def apply_overscan(self, distance_mm: builtins.float) -> None:
        r"""
        Apply overscan to raster lines.
        
        Extends raster line start/end points by ``distance_mm`` along
        the line direction, adding zero-power lead-in and lead-out
        segments for constant engraving velocity.
        
        :param distance_mm: Overscan distance in millimeters.
        """
    def apply_lead_in_out(self, lead_in_mm: builtins.float, lead_out_mm: builtins.float) -> None:
        r"""
        Apply lead-in and lead-out to vector contour paths.
        
        For each contour within a VECTOR_OUTLINE section, extends the
        toolpath with zero-power lead-in and lead-out segments along
        the tangent direction at the path start and end.
        
        :param lead_in_mm: Lead-in distance in millimeters.
        :param lead_out_mm: Lead-out distance in millimeters.
        """
    def optimize_travel(self, allow_flip: builtins.bool = True, preserve_first: builtins.bool = False, preserve_order: typing.Sequence[builtins.str] = [], progress_cb: typing.Optional[typing.Any] = None) -> None:
        r"""
        Optimize travel distance by reordering segments.
        
        Performs two-level optimization: workpiece-level reordering
        (when workpiece markers are present) and segment-level
        nearest-neighbor + 2-opt refinement.
        
        :param allow_flip: Whether to allow flipping subpaths.
        :param preserve_first: Keep the first workpiece in place.
        :param preserve_order: Workpiece UIDs whose order to preserve.
        :param progress_cb: Optional callable(progress, message).
        """

@typing.final
class OpsSection:
    r"""
    A section of operations parsed into marker and content index groups.
    
    Produced by :meth:`Ops.sections` when splitting an Ops sequence
    into logical sections based on ``OpsSectionStart``/``OpsSectionEnd`` markers.
    """
    @property
    def section_type(self) -> typing.Optional[types.SectionType]:
        r"""
        The type of this section (VectorOutline or RasterFill), if any.
        """
    @property
    def marker_indices(self) -> builtins.list[builtins.int]:
        r"""
        Indices of the section-marker commands (start/end) for this section.
        """
    @property
    def content_indices(self) -> builtins.list[builtins.int]:
        r"""
        Indices of the content commands belonging to this section.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class OpsSectionRange:
    r"""
    A contiguous range of indices that belong to a section.
    
    Similar to :class:`OpsSection` but stores start/end index ranges
    instead of individual index lists. Produced by :meth:`Ops.section_ranges`.
    """
    @property
    def section_type(self) -> typing.Optional[types.SectionType]:
        r"""
        The type of this section range (VectorOutline or RasterFill), if any.
        """
    @property
    def marker_indices(self) -> builtins.list[builtins.int]:
        r"""
        Indices of the section-marker commands that bracket this range.
        """
    @property
    def content_indices(self) -> builtins.list[builtins.int]:
        r"""
        Starting index of the content within this section range.
        """
    def __repr__(self) -> builtins.str: ...

