# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from raygeo.cnc import plan
from raygeo import ops
from raygeo.ops import part
from raygeo.pipeline import execute
import typing
__all__ = [
    "Intent",
    "create_intent",
    "run_intent",
]

@typing.final
class Intent:
    r"""
    An executable Intent produced by [`create_intent`].
    
    Holds the raw [`NodeRequest`]s inside a shared container so that
    [`run_intent`] can move them out at execution time.
    """
    @property
    def step_count(self) -> builtins.int:
        r"""
        Number of compute nodes in this intent (excluding the final aggregate).
        """
    def __repr__(self) -> builtins.str: ...

def create_intent(plan: plan.Plan, part: part.Part, generation_id: builtins.int) -> Intent:
    r"""
    Convert a Plan and Part into an executable Intent.
    """

def run_intent(intent: Intent, on_completed: typing.Optional[typing.Any] = None, on_batch_progress: typing.Optional[typing.Any] = None, pipeline: typing.Optional[execute.Pipeline] = None) -> ops.Ops:
    r"""
    Run an Intent through the pipeline, consuming the node list.
    
    Returns the final aggregated :class:`~raygeo.ops.Ops` (all steps
    linked with safe-Z travel).  ``on_completed`` is invoked for each
    completed node (including the aggregate) for progress monitoring.
    """

