# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import collections.abc
import raygeo
__all__ = [
    "execute_workplan",
]

def execute_workplan(steps: list[dict], pocket_boundary: collections.abc.Sequence[tuple[float, float]], islands: collections.abc.Sequence[collections.abc.Sequence[tuple[float, float]]] | None = None, cut_feed_rate: int = 1200, cut_power: float = 1, rapid_feed_rate: int | None = None) -> raygeo.ops.assembly.result.AssemblyResult:
    r"""
    Execute a workplan: dispatch each step to its assembler.
    
    Each entry in *steps* is a ``WorkplanStep`` dict as produced by a
    builder such as :func:`raygeo.cnc.machining.wavefront.build_wavefront_workplan`
    or :func:`raygeo.cnc.machining.entry.build_entry_workplan`. The
    executor owns a shared cleared area, asks each step to invoke its
    own assembler, and chains the results into a single
    :class:`AssemblyResult`.
    
    :param steps: List of WorkplanStep dicts (with a ``"kind"`` key).
    :param pocket_boundary: Outer boundary of the pocket.
    :param islands: List of island polygons (default None).
    :param cut_feed_rate: Feed rate for cutting moves (default 1200).
    :param cut_power: Laser power for cutting moves (default 1.0).
    :param rapid_feed_rate: Feed rate for travel/retract moves, or
        ``None`` to leave them unmodified (default None).
    :returns: The combined :class:`AssemblyResult`.
    """

