# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import collections.abc
import raygeo
__all__ = [
    "adaptive_wavefronts",
    "adaptive_wavefronts_multi_pocket",
]

def adaptive_wavefronts(part: raygeo.ops.part.Part, tool_radius: float = 3, step_over: float = 2, z: float = 0, area_tolerance: float = 1, precision: float = 0, cut_feed_rate: int = 1200, cut_power: float = 1) -> raygeo.ops.assembly.AssemblyResult:
    r"""
    Inside-out adaptive wavefronts.
    
    Starting from the cleared state inside *part*, each iteration
    expands the cleared boundary outward by *step_over*, clips to
    the valid tool area (pocket boundary offset inward by
    *tool_radius*, with islands excluded), and adds the result
    back to the part's cleared state.  The loop terminates when
    the newly added area drops below *area_tolerance*.
    
    Each ring fragment is emitted as ``MoveTo`` + ``LineTo`` at
    height *z* with *cut_feed_rate* applied.
    
    :param part: The part whose ``cleared`` field tracks accumulated
                 workpiece state and whose geometry defines the
                 pocket boundary and islands.
    :param tool_radius: Tool radius in mm (default 3.0).
    :param step_over: Radial expansion per iteration (default 2.0).
    :param z: Z height for generated commands (default 0.0).
    :param area_tolerance: Minimum area increase to continue (default 1.0).
    :param precision: Edge tolerance for frontier simplification and vertex
                      resampling; smaller values produce denser edges
                      (default 0.0 = use internal default).
    :param cut_feed_rate: Feed rate for cutting moves (default 1200).
    :param cut_power: Laser power for cutting moves (0.0-1.0, default 1.0).
    :returns: An :class:`AssemblyResult` with wavefront cutting commands.
    """

def adaptive_wavefronts_multi_pocket(part: raygeo.ops.part.Part, tool_radius: float = 3, step_over: float = 2, offset_mm: float = 0, area_tolerance: float = 0.01, precision: float = 0, cut_feed_rate: int = 1200, cut_power: float = 1) -> raygeo.ops.assembly.AssemblyResult:
    r"""
    Multi-pocket adaptive wavefronts.
    
    Extracts all pockets from *part.geometry*, optionally offsets
    the boundary inward by *offset_mm*, and runs a spiral-seed +
    wavefront expansion inside each pocket.  Returns the combined
    result.
    
    :param part: The part whose geometry defines the pockets.
    :param tool_radius: Tool radius in mm (default 3.0).
    :param step_over: Radial expansion per iteration (default 2.0).
    :param offset_mm: Inward offset applied to all contours (default 0.0).
    :param area_tolerance: Minimum area increase to continue (default 0.01).
    :param precision: Edge tolerance for frontier simplification (default 0.0).
    :param cut_feed_rate: Feed rate for cutting moves (default 1200).
    :param cut_power: Laser power for cutting moves (0.0-1.0, default 1.0).
    :returns: An :class:`AssemblyResult` with combined wavefront paths.
    :raises ValueError: If the part has no geometry or no closed contours.
    """

