# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import collections.abc
import raygeo
__all__ = [
    "adaptive_wavefronts",
]

def adaptive_wavefronts(part: raygeo.ops.cut.Part, cleared: raygeo.ops.cut.cleared_area.ClearedArea, tool_radius: float = 3, step_over: float = 2, z: float = 0, area_tolerance: float = 1, precision: float = 0, cut_feed_rate: int = 1200, cut_power: float = 1) -> raygeo.ops.assembly.result.AssemblyResult:
    r"""
    Inside-out adaptive wavefronts.
    
    Starting from the *cleared* state, each iteration expands the
    cleared boundary outward by *step_over*, clips to the valid tool
    area (pocket boundary offset inward by *tool_radius*, with
    islands excluded), and adds the result back to *cleared*.
    The loop terminates when the newly added area drops below
    *area_tolerance*.
    
    Each ring fragment is emitted as ``MoveTo`` + ``LineTo`` at
    height *z* with *cut_feed_rate* applied.
    
    :param cleared: ``ClearedArea`` instance (mutated in place).
    :param tool_radius: Tool radius in mm (default 3.0).
    :param step_over: Radial expansion per iteration (default 2.0).
    :param z: Z height for generated commands (default 0.0).
    :param area_tolerance: Minimum area increase to continue (default 1.0).
    :param precision: Edge tolerance for frontier simplification and vertex
                      resampling; smaller values produce denser edges
                      (default 0.0 = use internal default).
    :param cut_feed_rate: Feed rate for cutting moves (default 1200).
    :param cut_power: Laser power for cutting moves (0.0-1.0, default 1.0).
    :returns: An :class:`AssemblyResult` with wavefront cutting commands.
    """

