# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Feature detection for machining analysis.
"""

from . import narrow
from . import near
__all__ = [
    "narrow",
    "near",
]

