# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import collections.abc
import raygeo
__all__ = [
    "emit_resume_travel",
    "smooth_travel_path",
    "try_resume",
]

def emit_resume_travel(ops: raygeo.ops.Ops, to_pt: tuple[float, float], pocket_boundary: collections.abc.Sequence[tuple[float, float]], islands: collections.abc.Sequence[collections.abc.Sequence[tuple[float, float]]] = [], radius: float = 3, cut_z: float = -5) -> None:
    r"""
    Emit a resume travel to *to_pt* as a single straight-line ``move_to``.
    """

def smooth_travel_path(from_pt: tuple[float, float], raw: collections.abc.Sequence[tuple[float, float]], obstacles: collections.abc.Sequence[collections.abc.Sequence[tuple[float, float]]] = [], clearance: float = 1) -> list[tuple[float, float]]:
    r"""
    Smooth and shorten a cleared-territory travel path.
    """

def try_resume(cleared: raygeo.ops.cut.cleared_area.ClearedArea, ops: raygeo.ops.Ops, tool: raygeo.ops.assembly.adaptive.tool.Tool, pocket_boundary: collections.abc.Sequence[tuple[float, float]], islands: collections.abc.Sequence[collections.abc.Sequence[tuple[float, float]]] = [], radius: float = 3, step_length: float = 0.6, advance: float = 1.5, cut_z: float = -5, max_deflection_deg: float = 30, valid_tool_area: collections.abc.Sequence[collections.abc.Sequence[tuple[float, float]]] = [], axis: raygeo.geo.algo.medial_axis.MedialAxis | None = None, last_resume_area: float = -1, cut_direction: str = 'ccw', segment_start: tuple[float, float] = (0, 0), segment_heading: float = 0) -> bool:
    r"""
    Try to recover after the tool stalls or is detected as stuck.
    
    :param cut_direction: ``"cw"`` or ``"ccw"``.
    """

