# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Geometry types and operations for 2D/3D path data.

The central type is Geometry — a mutable sequence of drawing commands
(move, line, arc, bezier) that represents one or more closed or open
paths. Geometry supports construction (add_rect, add_circle, etc.),
analysis (area, distance, bounding rect), and manipulation (transform,
simplify, linearize, fit curves, grow/shrink, split, clip).

Shape sub-modules provide primitive-specific operations: arc bounding
and intersection, bezier splitting and flattening, circle containment
tests, polygon boolean algebra and offsetting, and line intersection.

Algorithm sub-modules provide higher-level geometric processing such
as polyline simplification, smoothing, curve fitting, and Minkowski
sums for toolpath generation.
"""

import builtins
import typing
from . import algo
from . import math
from . import shape
from . import types
__all__ = [
    "Arc",
    "Bezier",
    "Geometry",
    "Line",
    "Move",
    "algo",
    "math",
    "shape",
    "types",
]

@typing.final
class Arc:
    @property
    def end(self) -> tuple[builtins.float, builtins.float, builtins.float]: ...
    @property
    def center_offset(self) -> tuple[builtins.float, builtins.float]: ...
    @property
    def clockwise(self) -> builtins.bool: ...

@typing.final
class Bezier:
    @property
    def end(self) -> tuple[builtins.float, builtins.float, builtins.float]: ...
    @property
    def control1(self) -> tuple[builtins.float, builtins.float]: ...
    @property
    def control2(self) -> tuple[builtins.float, builtins.float]: ...

@typing.final
class Geometry:
    @property
    def last_move_to(self) -> tuple[builtins.float, builtins.float, builtins.float]:
        r"""
        The coordinates of the last move-to command.
        """
    @last_move_to.setter
    def last_move_to(self, value: tuple[builtins.float, builtins.float, builtins.float]) -> None: ...
    @property
    def uniform_scalable(self) -> builtins.bool:
        r"""
        Whether the geometry uses uniform scalable arcs.
        """
    @uniform_scalable.setter
    def uniform_scalable(self, value: builtins.bool) -> None: ...
    @property
    def data(self) -> builtins.list[typing.Any]:
        r"""
        The commands as a list of typed command objects.
        """
    def __eq__(self, other: object) -> bool:
        r"""
        Check equality with another Geometry.
        """
    def __ne__(self, other: object) -> bool:
        r"""
        Check inequality with another Geometry.
        """
    def transform(self, matrix: types.TransformMatrix) -> Geometry:
        r"""
        Apply a 4x4 affine transformation matrix.
        
        See ``raygeo.geo.types.TransformMatrix`` for the matrix layout.
        
        :param matrix: A 4x4 affine transformation matrix.
        :returns: A new transformed Geometry.
        """
    def iter_typed_commands(self) -> list[Move | Line | Arc | Bezier]:
        r"""
        Iterate over all commands as typed command objects.
        """
    def get_typed_command_at(self, index: int) -> Move | Line | Arc | Bezier | None:
        r"""
        Get the typed command at the given index.
        
        :param index: Command index.
        """
    def __new__(cls) -> Geometry:
        r"""
        Create a new empty Geometry.
        """
    def move_to(self, x: builtins.float, y: builtins.float, z: builtins.float = 0.0) -> None:
        r"""
        Move the pen to the given coordinates.
        
        :param x: X coordinate.
        :param y: Y coordinate.
        :param z: Z coordinate (default 0.0).
        """
    def line_to(self, x: builtins.float, y: builtins.float, z: builtins.float = 0.0) -> None:
        r"""
        Draw a line to the given coordinates.
        
        :param x: X coordinate.
        :param y: Y coordinate.
        :param z: Z coordinate (default 0.0).
        """
    def close_path(self) -> None:
        r"""
        Close the current sub-path.
        """
    def arc_to(self, x: builtins.float, y: builtins.float, i: builtins.float = 0.0, j: builtins.float = 0.0, clockwise: builtins.bool = True, z: builtins.float = 0.0) -> None:
        r"""
        Draw an arc to the given coordinates.
        
        :param x: X coordinate.
        :param y: Y coordinate.
        :param i: I offset from current point to center.
        :param j: J offset from current point to center.
        :param clockwise: Whether the arc is clockwise.
        :param z: Z coordinate (default 0.0).
        """
    def bezier_to(self, x: builtins.float, y: builtins.float, c1x: builtins.float, c1y: builtins.float, c2x: builtins.float, c2y: builtins.float, z: builtins.float = 0.0) -> None:
        r"""
        Draw a cubic bezier curve.
        
        :param x: End X coordinate.
        :param y: End Y coordinate.
        :param c1x: First control point X.
        :param c1y: First control point Y.
        :param c2x: Second control point X.
        :param c2y: Second control point Y.
        :param z: End Z coordinate (default 0.0).
        """
    def __len__(self) -> builtins.int:
        r"""
        Return the number of commands.
        """
    def __hash__(self) -> builtins.int:
        r"""
        Return a hash of the geometry data.
        """
    def is_empty(self) -> builtins.bool:
        r"""
        Check if the geometry has no commands.
        """
    def clear(self) -> None:
        r"""
        Remove all commands from the geometry.
        """
    def copy(self) -> Geometry:
        r"""
        Return a deep copy of this geometry.
        """
    def get_last_point(self) -> tuple[builtins.float, builtins.float, builtins.float]:
        r"""
        Get the last point in the geometry.
        """
    def extend(self, other: Geometry) -> None:
        r"""
        Append another geometry's commands to this one.
        
        :param other: The geometry to append.
        """
    def rect(self) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float]:
        r"""
        Return the bounding rectangle (x_min, x_max, y_min, y_max).
        """
    def segment_bounds(self, index: builtins.int) -> typing.Optional[tuple[builtins.float, builtins.float, builtins.float, builtins.float]]:
        r"""
        Return the bounding box of a single segment at the given index.
        Returns None for Move commands or if the index is out of bounds.
        
        :param index: Segment index.
        :returns: (x_min, y_min, x_max, y_max) or None.
        """
    def get_positions_at_distances(self, distances: typing.Sequence[builtins.float]) -> builtins.list[tuple[builtins.int, builtins.float, tuple[builtins.float, builtins.float]]]:
        r"""
        Given a list of distances along the path, returns the corresponding
        (segment_index, t, point) for each distance.
        
        Distances are clamped to [0, total_length].
        
        :param distances: List of distances along the path.
        :returns: List of (segment_index, t, (x, y)) tuples.
        """
    def segments_in_frame(self, x1: builtins.float, y1: builtins.float, x2: builtins.float, y2: builtins.float) -> builtins.list[builtins.int]:
        r"""
        Return indices of all segments whose bounding box intersects the
        given rectangle. Excludes Move commands.
        
        :param x1: First corner X.
        :param y1: First corner Y.
        :param x2: Second corner X.
        :param y2: Second corner Y.
        :returns: List of segment indices.
        """
    def distance(self) -> builtins.float:
        r"""
        Return the total path distance.
        """
    def area(self) -> builtins.float:
        r"""
        Return the signed area of the geometry.
        """
    def is_closed(self, tolerance: builtins.float = 1e-06) -> builtins.bool:
        r"""
        Check if the geometry forms a closed path.
        
        :param tolerance: Max gap between start and end point.
        """
    def segments(self) -> builtins.list[builtins.list[tuple[builtins.float, builtins.float, builtins.float]]]:
        r"""
        Return the geometry split into segments of connected commands.
        """
    def get_command_at(self, index: builtins.int) -> typing.Optional[typing.Any]:
        r"""
        Get the command at the given index as a typed command object.
        
        :param index: Command index (negative returns None).
        """
    def iter_commands(self) -> builtins.list[typing.Any]:
        r"""
        Iterate over all commands as typed command objects.
        """
    def to_dict(self) -> dict:
        r"""
        Serialize the geometry to a dictionary.
        """
    @classmethod
    def from_dict(cls, data: dict) -> Geometry:
        r"""
        Create a Geometry from a dictionary.
        
        :param data: A dictionary as produced by
            :meth:`to_dict`.
        """
    @classmethod
    def from_points(cls, points: typing.Any, close: builtins.bool = True) -> Geometry:
        r"""
        Create a Geometry from a sequence of points.
        
        :param points: A sequence of (x, y) or
            (x, y, z) coordinate tuples.
        :param close: Whether to close the path.
        """
    def filter(self, indices: builtins.set[builtins.int]) -> Geometry:
        r"""
        Return a new Geometry containing only commands at the given
        indices.
        
        :param indices: Set of command indices to keep.
        :returns: A new Geometry with the filtered commands.
        """
    def simplify(self, tolerance: builtins.float) -> Geometry:
        r"""
        Simplify the geometry using Ramer-Douglas-Peucker.
        
        :param tolerance: Maximum deviation from original.
        """
    def linearize(self, tolerance: builtins.float) -> Geometry:
        r"""
        Convert all curves to line segments.
        
        :param tolerance: Maximum deviation from curves.
        """
    def fit_curves(self, tolerance: builtins.float, beziers: builtins.bool = True, arcs: builtins.bool = True, on_progress: typing.Optional[typing.Any] = None) -> Geometry:
        r"""
        Fit curves (beziers and arcs) to the linearized geometry.
        
        :param tolerance: Maximum deviation.
        :param beziers: Whether to fit bezier curves.
        :param arcs: Whether to fit arcs.
        :param on_progress: Optional progress callback.
        """
    def fit_arcs(self, tolerance: builtins.float) -> Geometry:
        r"""
        Fit arcs only to the linearized geometry.
        
        :param tolerance: Maximum deviation.
        """
    def upgrade_to_scalable(self) -> Geometry:
        r"""
        Convert all arcs to bezier curves for uniform scaling.
        """
    def close_gaps(self, tolerance: typing.Optional[builtins.float] = None) -> Geometry:
        r"""
        Close gaps between sub-paths.
        
        :param tolerance: Max gap to close.
        """
    def cleanup(self, tolerance: builtins.float) -> Geometry:
        r"""
        Remove duplicate segments from the geometry.
        
        :param tolerance: Maximum deviation for equality.
        """
    def flip_x(self) -> Geometry:
        r"""
        Mirror the geometry along the X axis.
        """
    def flip_y(self) -> Geometry:
        r"""
        Mirror the geometry along the Y axis.
        """
    def find_closest_point(self, x: builtins.float, y: builtins.float) -> typing.Optional[tuple[builtins.int, builtins.float, tuple[builtins.float, builtins.float]]]:
        r"""
        Find the closest point on the path to (x, y).
        
        :param x: X coordinate.
        :param y: Y coordinate.
        :returns: Tuple of (segment_index, t, point) or None.
        """
    def get_point_at(self, segment_index: builtins.int, t: builtins.float) -> typing.Optional[tuple[builtins.float, builtins.float, builtins.float]]:
        r"""
        Get the point at parameter t on a segment.
        
        :param segment_index: Index of the segment.
        :param t: Parameter in [0, 1].
        :returns: The 3D point or None.
        """
    def get_tangent_at(self, segment_index: builtins.int, t: builtins.float) -> typing.Optional[tuple[builtins.float, builtins.float]]:
        r"""
        Get the tangent vector at parameter t on a segment.
        
        :param segment_index: Index of the segment.
        :param t: Parameter in [0, 1].
        :returns: The normalized tangent vector or None.
        """
    def get_outward_normal_at(self, segment_index: builtins.int, t: builtins.float) -> typing.Optional[tuple[builtins.float, builtins.float]]:
        r"""
        Get the outward normal at parameter t on a segment.
        
        :param segment_index: Index of the segment.
        :param t: Parameter in [0, 1].
        :returns: Normal vector or None.
        """
    def arc_to_as_bezier(self, x: builtins.float, y: builtins.float, i: builtins.float, j: builtins.float, clockwise: builtins.bool = True, z: builtins.float = 0.0) -> None:
        r"""
        Draw an arc, converting it to bezier curves.
        
        :param x: End X coordinate.
        :param y: End Y coordinate.
        :param i: I offset to center.
        :param j: J offset to center.
        :param clockwise: Arc direction.
        :param z: End Z coordinate.
        """
    def has_self_intersections(self, fail_on_t_junction: builtins.bool = False) -> builtins.bool:
        r"""
        Check if the geometry has self-intersections.
        
        :param fail_on_t_junction: Whether to fail on T-junctions.
        """
    def intersects_with(self, other: Geometry) -> builtins.bool:
        r"""
        Check if this geometry intersects with another.
        
        :param other: The other geometry.
        """
    def grow(self, amount: builtins.float) -> Geometry:
        r"""
        Offset (grow/shrink) the geometry by the given amount.
        
        :param amount: Positive to grow, negative to shrink.
        """
    def encloses(self, other: Geometry) -> builtins.bool:
        r"""
        Check if this geometry encloses another.
        
        :param other: The potentially enclosed geometry.
        """
    def remove_inner_edges(self) -> Geometry:
        r"""
        Remove inner edges (shared between contours).
        """
    def split_inner_and_outer_contours(self) -> tuple[builtins.list[Geometry], builtins.list[Geometry]]:
        r"""
        Split contours into inner and outer groups.
        """
    def map_to_frame(self, origin: tuple[builtins.float, builtins.float], p_width: tuple[builtins.float, builtins.float], p_height: tuple[builtins.float, builtins.float], anchor_y: typing.Optional[builtins.float] = None, stable_src_height: typing.Optional[builtins.float] = None, anchor_x: typing.Optional[builtins.float] = None, stable_src_width: typing.Optional[builtins.float] = None) -> Geometry:
        r"""
        Map the geometry into a rectangular frame.
        
        :param origin: Frame origin (x, y).
        :param p_width: Frame width vector.
        :param p_height: Frame height vector.
        :param anchor_y: Y anchor position.
        :param stable_src_height: Stable source height for anchoring.
        :param anchor_x: X anchor position.
        :param stable_src_width: Stable source width for anchoring.
        """
    def split_into_contours(self) -> builtins.list[Geometry]:
        r"""
        Split the geometry into individual contours.
        """
    def split_into_components(self) -> builtins.list[Geometry]:
        r"""
        Split the geometry into connected components.
        """
    def to_polygons(self, tolerance: builtins.float = 0.01) -> builtins.list[builtins.list[tuple[builtins.float, builtins.float]]]:
        r"""
        Convert the geometry to a list of polygons.
        
        :param tolerance: Max deviation for linearization.
        """
    def reverse_contour(self) -> Geometry:
        r"""
        Reverse the winding direction of all contours.
        """
    def close_all_contours(self) -> Geometry:
        r"""
        Close all open contours in the geometry.
        """
    def normalize_winding_orders(self) -> builtins.list[Geometry]:
        r"""
        Normalize winding orders (outer CCW, inner CW) of all contours.
        """
    def filter_to_external_contours(self) -> builtins.list[Geometry]:
        r"""
        Filter to only external (outermost) contours.
        """
    def get_valid_contours_data(self) -> builtins.list[dict]:
        r"""
        Get valid contour data from the geometry's contours.
        
        :returns: List of dicts with keys "geo", "vertices",
            "is_closed", "original_index".
        """
    def __repr__(self) -> builtins.str:
        r"""
        Return a string representation of the geometry.
        """

@typing.final
class Line:
    @property
    def end(self) -> tuple[builtins.float, builtins.float, builtins.float]: ...

@typing.final
class Move:
    @property
    def end(self) -> tuple[builtins.float, builtins.float, builtins.float]: ...

