# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Polygon offsetting operations for geometry data.

Provides concentric inward offset generation for adaptive clearing
and pocketing toolpath generation.
"""

import collections.abc
import raygeo
__all__ = [
    "concentric_offsets",
]

def concentric_offsets(geom: raygeo.Geometry, step: float, max_passes: int = 10, min_area: float = 1) -> list[raygeo.Geometry]:
    r"""
    Generate concentric inward offsets of a geometry.
    
    Each successive offset shrinks the boundary by `step`. Stops early
    when the enclosed area drops below `min_area` or `max_passes` is
    reached. Returns offsets outermost-first.
    
    :param geom: A closed geometry.
    :param step: Inward offset distance per pass.
    :param max_passes: Maximum number of offset passes (default 10).
    :param min_area: Minimum area to stop at (default 1.0).
    :returns: List of offset geometries, outermost first.
    :complexity: O(n * p) time, O(n) space where n is the number of contour vertices and p the number of passes
    """

