# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import numpy
import raygeo
__all__ = [
    "shrinkwrap",
]

def shrinkwrap(part: raygeo.Part, image: numpy.ndarray, gravity: float = 0.1, kerf_mm: float = 0, path_offset_mm: float = 0, cut_side: str = 'centerline', arc_tolerance: float = 0, allow_arcs: bool = True, supports_curves: bool = False) -> raygeo.ops.assembly.result.AssemblyResult:
    r"""
    Generate a shrink-wrapped (concave hull) contour around image content.
    
    Computes a concave hull from the binary *image* using Bézier
    gravity attraction, transforms pixel coordinates to millimetre
    space via the part's *size_mm* and image dimensions, computes
    the total offset from kerf / path-offset / cut-side, applies
    it, optionally fits arcs/curves when *arc_tolerance* > 0, and
    returns the result as an :class:`AssemblyResult`.
    
    :param part: Part providing physical size metadata.
    :param image: 2D boolean or binary numpy array.
    :param gravity: Shrink-wrap factor 0.0–1.0 (0 = convex hull,
        default 0.1).
    :param kerf_mm: Tool kerf width in mm (default 0.0).
    :param path_offset_mm: Additional offset distance in mm
        (default 0.0).
    :param cut_side: ``"centerline"``, ``"outside"``, or
        ``"inside"`` (default ``"centerline"``).
    :param arc_tolerance: Curve fitting tolerance in mm (default 0.0).
    :param allow_arcs: Fit arcs when arc_tolerance > 0 (default True).
    :param supports_curves: Keep Bézier curves when arc_tolerance > 0
        (default False).
    :returns: An :class:`AssemblyResult` with the shrinkwrap path.
    :raises ValueError: If the image is empty or the part has no size.
    """

