# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
SVG color attribute selection.

Selects which color attribute (fill, stroke, fill-else-stroke, or any)
determines the color bucket of a shape.
"""

import enum
import typing
__all__ = [
    "ColorAttr",
]

@typing.final
class ColorAttr(enum.Enum):
    r"""
    Which color attribute of a shape determines its color bucket.
    
    ``FILL_ELSE_STROKE`` uses the fill color when present, otherwise the
    stroke color. ``ANY`` buckets a shape by both its fill and its stroke
    when they differ, producing two layers (one per color).
    """
    FILL = ...
    r"""
    Bucket by the resolved `fill` paint.
    """
    STROKE = ...
    r"""
    Bucket by the resolved `stroke` paint.
    """
    FILL_ELSE_STROKE = ...
    r"""
    Use the fill paint when present, otherwise the stroke paint.
    """
    ANY = ...
    r"""
    Bucket by both fill and stroke when they differ, producing two
    layers (one per color).
    """

