# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
SVG length parsing and unit conversion.

Parses SVG length strings such as '10mm' or '2.5in' and converts
between millimetres, pixels and other CSS units.
"""

__all__ = [
    "parse_svg_length",
    "svg_length_to_mm",
    "svg_length_to_px",
]

def parse_svg_length(length_str: str) -> tuple[float, str]:
    r"""
    Parse an SVG length string into a (value, unit) tuple.
    
    Supports: mm, cm, in, pt, pc, px. Unitless values default to 'px'.
    
    :param length_str: SVG length string (e.g. '10mm', '2.5in', '100').
    :returns: Tuple of (value, unit).
    :complexity: O(1)
    """

def svg_length_to_mm(length_str: str, dpi: float = 96) -> float:
    r"""
    Parse an SVG length string and convert to millimetres.
    
    :param length_str: SVG length string (e.g. '10mm', '2.5in', '100').
    :param dpi: Pixels per inch used for px/unitless conversion (default 96).
    :returns: Length in millimetres.
    :complexity: O(1)
    """

def svg_length_to_px(length_str: str, dpi: float = 96) -> float:
    r"""
    Parse an SVG length string and convert to pixels.
    
    :param length_str: SVG length string (e.g. '10mm', '2.5in', '100').
    :param dpi: Pixels per inch used for px/unitless conversion (default 96).
    :returns: Length in pixels.
    :complexity: O(1)
    """

