# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Placement search and collision detection for nesting algorithms.

Provides candidate generation strategies (bottom-left, grid, perimeter),
collision detection with spatial indexing, and high-level nesting orchestration.
"""

import collections.abc
from raygeo.geo import types
__all__ = [
    "any_overlap",
    "filter_candidates_multi_resolution",
    "find_valid_position",
    "generate_bottom_left_candidates",
    "generate_grid_candidates",
    "generate_perimeter_candidates",
    "is_contained",
    "place_parts",
]

def any_overlap(candidate: types.Polygon, placed: collections.abc.Sequence[types.Polygon], min_area: float = 1) -> bool:
    r"""
    Check if a candidate polygon overlaps any placed polygon.
    
    :param candidate: Candidate polygon.
    :param placed: List of already-placed polygons.
    :param min_area: Minimum overlap area to consider (in clipper coords).
    :returns: True if any overlap detected.
    """

def filter_candidates_multi_resolution(candidates: list[tuple[float, float]], ifp_bounds: tuple[float, float, float, float], min_dist: float) -> list[tuple[float, float]]:
    r"""
    Remove candidates that are too close together.
    
    :param candidates: List of (x, y) candidate positions.
    :param ifp_bounds: IFP bounding box (min_x, min_y, max_x, max_y).
    :param min_dist: Minimum allowed distance between candidates.
    :returns: Filtered list of (x, y) positions.
    """

def find_valid_position(ifp_polygons: collections.abc.Sequence[types.Polygon], part_polygons: collections.abc.Sequence[types.Polygon], placed_polygons: collections.abc.Sequence[types.Polygon], spacing: float, scale: int, min_area: float = 1) -> tuple[float, float] | None:
    r"""
    Find the first valid placement position for a part.
    
    :param ifp_polygons: IFP polygons (valid placement region).
    :param part_polygons: Part polygons to place.
    :param placed_polygons: Already-placed polygons.
    :param spacing: Minimum spacing between parts.
    :param scale: Clipper scale factor.
    :param min_area: Minimum overlap area (clipper coords).
    :returns: (x, y) position or None.
    """

def generate_bottom_left_candidates(ifp_bounds: tuple[float, float, float, float], part_bounds: tuple[float, float, float, float], spacing: float) -> list[tuple[float, float]]:
    r"""
    Generate candidate positions scanning from bottom-left.
    
    :param ifp_bounds: IFP bounding box (min_x, min_y, max_x, max_y).
    :param part_bounds: Part bounding box (min_x, min_y, max_x, max_y).
    :param spacing: Minimum spacing between parts.
    :returns: List of (x, y) candidate positions.
    """

def generate_grid_candidates(ifp_bounds: tuple[float, float, float, float], part_bounds: tuple[float, float, float, float], spacing: float) -> list[tuple[float, float]]:
    r"""
    Generate candidate positions in a grid pattern.
    
    :param ifp_bounds: IFP bounding box (min_x, min_y, max_x, max_y).
    :param part_bounds: Part bounding box (min_x, min_y, max_x, max_y).
    :param spacing: Grid spacing.
    :returns: List of (x, y) candidate positions.
    """

def generate_perimeter_candidates(placed_groups: collections.abc.Sequence[collections.abc.Sequence[types.Polygon]], part_bounds: tuple[float, float, float, float], spacing: float) -> list[tuple[float, float]]:
    r"""
    Generate edge-aligned candidates around placed parts.
    
    For each placed part (group of polygons), produces 8 positions:
    right-bottom, right-top, left-bottom, left-top, above-left,
    above-right, below-left, below-right.
    
    :param placed_groups: List of placed parts, each a list of polygons.
    :param part_bounds: Part bounding box (min_x, min_y, max_x, max_y).
    :param spacing: Minimum spacing between parts.
    :returns: List of (x, y) candidate positions.
    """

def is_contained(inner: collections.abc.Sequence[types.Polygon], outer: types.Polygon, scale: int) -> bool:
    r"""
    Check if inner polygons are fully contained within outer polygon.
    
    :param inner: List of polygons to check.
    :param outer: Outer polygon.
    :param scale: Clipper scale factor.
    :returns: True if all inner polygons are inside outer.
    """

def place_parts(parts: collections.abc.Sequence[collections.abc.Sequence[types.Polygon]], sheets: collections.abc.Sequence[types.Polygon], rotations: collections.abc.Sequence[float], spacing: float, scale: int, min_area: float = 1) -> list[dict]:
    r"""
    Place as many parts as possible onto sheets.
    
    Each part is a list of polygons (holes are separate polygons).
    Each sheet is a single polygon.
    
    :param parts: List of parts (each part is a list of polygons).
    :param sheets: List of sheet polygons.
    :param rotations: List of rotation angles in degrees.
    :param spacing: Minimum spacing between parts.
    :param scale: Clipper scale factor.
    :param min_area: Minimum overlap area (clipper coords).
    :returns: List of dicts, one per sheet, with keys:
              ``placements``, ``sheet_index``, ``unused_part_indices``.
    """

