# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Burn-grid helpers: per-vertex power UVs for a stock mesh.
"""

import collections.abc
import numpy.typing
__all__ = [
    "compute_power_uvs",
]

def compute_power_uvs(positions: numpy.typing.NDArray[numpy.float32], origin_mm: tuple[float, float], px_per_mm: tuple[float, float], size_px: tuple[int, int]) -> numpy.typing.NDArray[numpy.float32]:
    r"""
    Map vertex positions onto a burn power grid as UVs.
    
    :param positions: Flat mesh vertex positions, shape ``(N, 3)``.
    :param origin_mm: World-mm coordinate of the grid's ``(0, 0)``
        pixel corner.
    :param px_per_mm: Grid density in pixels per millimetre.
    :param size_px: Grid size in pixels ``(width, height)``.
    :returns: ``(N, 2)`` power UVs index-aligned with *positions*.
    """

