r"""Geometry types and operations for 2D/3D path data.

Provides the Geometry class, path submodules for analysis/cleanup/intersection,
shape submodules (arc, bezier, circle, line, polygon, rect, point),
and algorithm submodules (clipping, fitting, minkowski, simplify, smooth).
"""

# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

from typing import TypeAlias
from . import algo
from . import path
from . import shape
__all__ = [
    "Point3D",
    "Polygon",
    "TransformMatrix",
    "algo",
    "path",
    "shape",
]

Point3D: TypeAlias = tuple[float, float] | tuple[float, float, float]
Polygon: TypeAlias = list[Point3D]
TransformMatrix: TypeAlias = list[list[float]] | numpy.ndarray[tuple[int, int], float]
