# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

__all__ = [
    "apply_affine_transform_to_array",
    "are_points_equal",
    "are_segments_equal",
    "check_intersection",
    "check_intersection_from_array",
    "check_self_intersection",
    "check_self_intersection_from_array",
    "convert_arc_to_beziers_from_array",
    "create_arc_cmd",
    "create_line_cmd",
    "extract_overcut_rows",
    "fit_arcs",
    "fit_curves",
    "flatten_to_points",
    "get_angle_at_vertex",
    "get_area_from_array",
    "get_bounding_rect_from_array",
    "get_outward_normal_at_from_array",
    "get_path_winding_order_from_array",
    "get_point_and_tangent_at",
    "get_segment_key",
    "get_subpath_area_from_array",
    "get_subpath_vertices_from_array",
    "get_total_distance_from_array",
    "is_clockwise",
    "is_closed",
    "linearize_geometry",
    "optimize_path_from_array",
    "remove_duplicate_segments",
    "remove_duplicates",
]

def apply_affine_transform_to_array(data: Sequence[Sequence[float]], matrix: Sequence[Sequence[float]]) -> Any:
    r"""
    Apply an affine transform to path data.
    
    :param data: Array of command data.
    :param matrix: 4x4 affine transformation matrix.
    :returns: Numpy array of transformed data.
    """

def are_points_equal(p1: Point3D, p2: Point3D, tolerance: float) -> bool:
    r"""
    Check if two 3D points are equal within tolerance.
    
    :param p1: First point (x, y, z).
    :param p2: Second point (x, y, z).
    :param tolerance: Maximum allowed difference.
    :returns: True if points are equal within tolerance.
    """

def are_segments_equal(key1: Any, key2: Any, tolerance: float) -> bool:
    r"""
    Check if two segment keys are equal within tolerance.
    
    :param key1: First segment key tuple.
    :param key2: Second segment key tuple.
    :param tolerance: Maximum allowed difference.
    :returns: True if segment keys are equal within tolerance.
    """

def check_intersection(data1: Optional[Sequence[Sequence[float]]], data2: Optional[Sequence[Sequence[float]]], fail_on_t_junction: bool) -> bool:
    r"""
    Check if two paths intersect.
    
    :param data1: First array of command data or None.
    :param data2: Second array of command data or None.
    :param fail_on_t_junction: Whether T-junctions count as intersections.
    :returns: True if intersections are found.
    """

def check_intersection_from_array(data1: Sequence[Sequence[float]], data2: Sequence[Sequence[float]], fail_on_t_junction: bool) -> bool:
    r"""
    Check intersection between two arrays.
    
    :param data1: First array of command data.
    :param data2: Second array of command data.
    :param fail_on_t_junction: Whether T-junctions count as intersections.
    :returns: True if intersections are found.
    """

def check_self_intersection(data: Optional[Sequence[Sequence[float]]], fail_on_t_junction: bool) -> bool:
    r"""
    Check if a path has self-intersections.
    
    :param data: Array of command data or None.
    :param fail_on_t_junction: Whether T-junctions count as intersections.
    :returns: True if self-intersections are found.
    """

def check_self_intersection_from_array(data: Sequence[Sequence[float]], fail_on_t_junction: bool) -> bool:
    r"""
    Check self-intersection from array data.
    
    :param data: Array of command data.
    :param fail_on_t_junction: Whether T-junctions count as intersections.
    :returns: True if self-intersections are found.
    """

def convert_arc_to_beziers_from_array(start: Point3D, end: Point3D, center_offset: Point, clockwise: bool) -> list[list[float]]:
    r"""
    Convert an arc to bezier curves.
    
    :param start: Start point (x, y, z).
    :param end: End point (x, y, z).
    :param center_offset: Center offset (dx, dy).
    :param clockwise: Whether the arc is clockwise.
    :returns: List of bezier command rows.
    """

def create_arc_cmd(end: Point3D, center: Point, start: Point3D) -> list[float]:
    r"""
    Create an arc command array.
    
    :param end: End point (x, y, z).
    :param center: Center offset (dx, dy).
    :param start: Start point (x, y, z).
    :returns: Arc command array (8 floats).
    """

def create_line_cmd(end_point: Point2DOr3D) -> list[float]:
    r"""
    Create a line command array from an end point.
    
    :param end_point: End point (x, y) or (x, y, z).
    :returns: Line command array (8 floats).
    """

def extract_overcut_rows(data: Optional[Sequence[Sequence[float]]], max_length: float) -> Optional[Any]:
    r"""
    Extract rows that exceed a maximum length.
    
    :param data: Array of command data or None.
    :param max_length: Maximum allowed segment length.
    :returns: Numpy array of overcut rows, or None.
    """

def fit_arcs(data: Optional[Sequence[Sequence[float]]], tolerance: float, progress_callback: Optional[Callable[[float], None]] = None) -> Optional[list[list[float]]]:
    r"""
    Fit arcs to a path.
    
    :param data: Array of command data or None.
    :param tolerance: Fitting tolerance.
    :param progress_callback: Optional progress callback.
    :returns: Fitted arc data or None.
    """

def fit_curves(data: Optional[Sequence[Sequence[float]]], tolerance: float, preserve_beziers: bool, preserve_arcs: bool) -> Any:
    r"""
    Fit curves (lines, arcs, beziers) to path data.
    
    :param data: Array of command data or None.
    :param tolerance: Fitting tolerance.
    :param preserve_beziers: Whether to preserve existing beziers.
    :param preserve_arcs: Whether to preserve existing arcs.
    :returns: Numpy array of fitted curve data.
    """

def flatten_to_points(data: Optional[Sequence[Sequence[float]]], tolerance: float) -> list[list[Point3D]]:
    r"""
    Flatten curves into linear segments.
    
    :param data: Array of command data or None.
    :param tolerance: Flattening tolerance.
    :returns: List of flattened point segments.
    """

def get_angle_at_vertex(p0: Point, p1: Point, p2: Point) -> float:
    r"""
    Get the angle at a vertex between three points.
    
    :param p0: First point.
    :param p1: Vertex point.
    :param p2: Third point.
    :returns: Angle in radians.
    """

def get_area_from_array(data: Sequence[Sequence[float]]) -> float:
    r"""
    Compute the total area of path data.
    
    :param data: Array of command data.
    :returns: Total signed area.
    """

def get_bounding_rect_from_array(data: Sequence[Sequence[float]]) -> Rect:
    r"""
    Compute the bounding rectangle of path data.
    
    :param data: Array of command data (rows of 8 floats).
    :returns: Bounding rectangle as (x_min, y_min, x_max, y_max).
    """

def get_outward_normal_at_from_array(data: Sequence[Sequence[float]], row_index: int, t: float) -> Optional[Point]:
    r"""
    Get the outward normal at a point on a segment.
    
    :param data: Array of command data.
    :param row_index: Row index of the segment.
    :param t: Parameter value along the segment (0..1).
    :returns: Outward normal vector (nx, ny) or None.
    """

def get_path_winding_order_from_array(data: Sequence[Sequence[float]], start_cmd_index: int) -> str:
    r"""
    Get the winding order (CW/CCW) of a path.
    
    :param data: Array of command data.
    :param start_cmd_index: Index of the first command of the path.
    :returns: Winding order as "CW" or "CCW".
    """

def get_point_and_tangent_at(data: Sequence[Sequence[float]], row_index: int, t: float) -> Optional[tuple[Point, Point]]:
    r"""
    Get the point and tangent at a parameter t on a segment.
    
    :param data: Array of command data.
    :param row_index: Row index of the segment.
    :param t: Parameter value along the segment (0..1).
    :returns: Tuple of (point, tangent) or None.
    """

def get_segment_key(data: Sequence[Sequence[float]], index: int, tolerance: float) -> Optional[Any]:
    r"""
    Get a segment key for comparison.
    
    :param data: Array of command data.
    :param index: Row index.
    :param tolerance: Tolerance for comparison.
    :returns: Tuple key or None.
    """

def get_subpath_area_from_array(data: Sequence[Sequence[float]], subpath_index: int) -> float:
    r"""
    Get the signed area of a subpath.
    
    :param data: Array of command data.
    :param subpath_index: Index of the subpath.
    :returns: Signed area of the subpath.
    """

def get_subpath_vertices_from_array(data: Sequence[Sequence[float]], subpath_index: int) -> Polygon:
    r"""
    Get the vertices of a subpath.
    
    :param data: Array of command data.
    :param subpath_index: Index of the subpath.
    :returns: List of vertex points (x, y).
    """

def get_total_distance_from_array(data: Sequence[Sequence[float]]) -> float:
    r"""
    Compute the total distance of a path.
    
    :param data: Array of command data.
    :returns: Total path length.
    """

def is_clockwise(points: Sequence[Point]) -> bool:
    r"""
    Check if a polygon has clockwise winding order.
    
    :param points: Sequence of (x, y) points defining a polygon.
    :returns: True if the winding is clockwise.
    """

def is_closed(commands: Sequence[Sequence[float]], tolerance: float = 0.000001) -> bool:
    r"""
    Check if a path is closed.
    
    :param commands: Array of command data.
    :param tolerance: Tolerance for end-to-start distance check.
    :returns: True if the path is closed.
    """

def linearize_geometry(data: Optional[Sequence[Sequence[float]]], tolerance: float) -> Any:
    r"""
    Linearize geometry data into line segments.
    
    :param data: Array of command data or None.
    :param tolerance: Linearization tolerance.
    :returns: Numpy array of linearized segments.
    """

def optimize_path_from_array(data: Optional[Sequence[Sequence[float]]], tolerance: float, fit_arcs: bool) -> Any:
    r"""
    Optimize a path by fitting arcs.
    
    :param data: Array of command data or None.
    :param tolerance: Fitting tolerance.
    :param fit_arcs: Whether to fit arcs (vs. only lines).
    :returns: Numpy array of optimized path data.
    """

def remove_duplicate_segments(data: Optional[Sequence[Sequence[float]]], tolerance: float = 0.000001) -> Any:
    r"""
    Remove duplicate segments from path data.
    
    :param data: Array of command data or None.
    :param tolerance: Comparison tolerance.
    :returns: Numpy array with duplicates removed.
    """

def remove_duplicates(points: Sequence[Point]) -> Polygon:
    r"""
    Remove duplicate points from a sequence.
    
    :param points: Sequence of (x, y) points.
    :returns: List of unique points.
    """

