# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

__all__ = [
    "apply_affine_transform_to_array",
    "check_intersection",
    "check_intersection_from_array",
    "check_self_intersection",
    "check_self_intersection_from_array",
    "close_all_contours",
    "close_geometry_gaps",
    "convert_arc_to_beziers_from_array",
    "create_arc_cmd",
    "create_line_cmd",
    "does_enclose",
    "extract_overcut_rows",
    "filter_to_external_contours",
    "fit_arcs",
    "fit_curves",
    "flatten_to_points",
    "get_angle_at_vertex",
    "get_area_from_array",
    "get_bounding_rect_from_array",
    "get_outward_normal_at_from_array",
    "get_path_winding_order_from_array",
    "get_point_and_tangent_at",
    "get_subpath_area_from_array",
    "get_subpath_vertices_from_array",
    "get_total_distance_from_array",
    "grow_geometry",
    "is_clockwise",
    "is_closed",
    "linearize_geometry",
    "map_geometry_to_frame",
    "normalize_winding_orders",
    "optimize_path_from_array",
    "remove_duplicate_segments",
    "remove_duplicates",
    "remove_inner_edges",
    "reverse_contour",
    "split_inner_and_outer_contours",
    "split_into_components",
    "split_into_contours",
]

def apply_affine_transform_to_array(data: Sequence[Sequence[float]], matrix: Sequence[Sequence[float]]) -> Any:
    r"""
    Apply an affine transform to path data.
    """

def check_intersection(data1: Optional[Sequence[Sequence[float]]], data2: Optional[Sequence[Sequence[float]]], fail_on_t_junction: bool) -> bool:
    r"""
    Check if two paths intersect.
    """

def check_intersection_from_array(data1: Sequence[Sequence[float]], data2: Sequence[Sequence[float]], fail_on_t_junction: bool) -> bool:
    r"""
    Check intersection between two arrays.
    """

def check_self_intersection(data: Optional[Sequence[Sequence[float]]], fail_on_t_junction: bool) -> bool:
    r"""
    Check if a path has self-intersections.
    """

def check_self_intersection_from_array(data: Sequence[Sequence[float]], fail_on_t_junction: bool) -> bool:
    r"""
    Check self-intersection from array data.
    """

def close_all_contours(geometry: Geometry) -> Geometry:
    r"""
    Close all open contours in a geometry.
    """

def close_geometry_gaps(geometry: Geometry, tolerance: float) -> Geometry:
    r"""
    Close gaps in a geometry.
    """

def convert_arc_to_beziers_from_array(start: tuple[float, float, float], end: tuple[float, float, float], center_offset: tuple[float, float], clockwise: bool) -> list[list[float]]:
    r"""
    Convert an arc to bezier curves.
    """

def create_arc_cmd(end: tuple[float, float, float], center: tuple[float, float], start: tuple[float, float, float]) -> list[float]:
    r"""
    Create an arc command array.
    """

def create_line_cmd(end_point: tuple[float, float, float]) -> list[float]:
    r"""
    Create a line command array from an end point.
    """

def does_enclose(container: Geometry, content: Geometry) -> bool:
    r"""
    Check if one geometry encloses another.
    """

def extract_overcut_rows(data: Optional[Sequence[Sequence[float]]], max_length: float) -> Optional[Any]:
    r"""
    Extract rows that exceed a maximum length.
    """

def filter_to_external_contours(contours: list[Geometry]) -> list[Geometry]:
    r"""
    Filter to only external (outer) contours.
    """

def fit_arcs(data: Optional[Sequence[Sequence[float]]], tolerance: float) -> Optional[list[list[float]]]:
    r"""
    Fit arcs to a path.
    """

def fit_curves(data: Optional[Sequence[Sequence[float]]], tolerance: float, preserve_beziers: bool, preserve_arcs: bool) -> Any:
    r"""
    Fit curves (lines, arcs, beziers) to path data.
    """

def flatten_to_points(data: Optional[Sequence[Sequence[float]]], tolerance: float) -> list[list[tuple[float, float, float]]]:
    r"""
    Flatten curves into linear segments.
    """

def get_angle_at_vertex(p0: tuple[float, float], p1: tuple[float, float], p2: tuple[float, float]) -> float:
    r"""
    Get the angle at a vertex between three points.
    """

def get_area_from_array(data: Sequence[Sequence[float]]) -> float:
    r"""
    Compute the total area of path data.
    """

def get_bounding_rect_from_array(data: Sequence[Sequence[float]]) -> tuple[float, float, float, float]:
    r"""
    Compute the bounding rectangle of path data.
    """

def get_outward_normal_at_from_array(data: Sequence[Sequence[float]], row_index: int, t: float) -> Optional[tuple[float, float]]:
    r"""
    Get the outward normal at a point on a segment.
    """

def get_path_winding_order_from_array(data: Sequence[Sequence[float]], start_cmd_index: int) -> str:
    r"""
    Get the winding order (CW/CCW) of a path.
    """

def get_point_and_tangent_at(data: Sequence[Sequence[float]], row_index: int, t: float) -> Optional[tuple[tuple[float, float], tuple[float, float]]]:
    r"""
    Get the point and tangent at a parameter t on a segment.
    """

def get_subpath_area_from_array(data: Sequence[Sequence[float]], subpath_index: int) -> float:
    r"""
    Get the signed area of a subpath.
    """

def get_subpath_vertices_from_array(data: Sequence[Sequence[float]], subpath_index: int) -> list[tuple[float, float]]:
    r"""
    Get the vertices of a subpath.
    """

def get_total_distance_from_array(data: Sequence[Sequence[float]]) -> float:
    r"""
    Compute the total distance of a path.
    """

def grow_geometry(geometry: Geometry, offset: float) -> Geometry:
    r"""
    Grow (offset) a geometry by a given amount.
    """

def is_clockwise(points: Sequence[tuple[float, float]]) -> bool:
    r"""
    Check if a polygon has clockwise winding order.
    """

def is_closed(commands: Sequence[Sequence[float]], tolerance: float = 0.000001) -> bool:
    r"""
    Check if a path is closed.
    """

def linearize_geometry(data: Optional[Sequence[Sequence[float]]], tolerance: float) -> Any:
    r"""
    Linearize geometry data into line segments.
    """

def map_geometry_to_frame(geometry: Geometry, origin: tuple[float, float], p_width: tuple[float, float], p_height: tuple[float, float], anchor_y: Optional[float] = None, stable_src_height: Optional[float] = None, anchor_x: Optional[float] = None, stable_src_width: Optional[float] = None) -> Geometry:
    r"""
    Map a geometry into a rectangular frame.
    """

def normalize_winding_orders(contours: list[Geometry]) -> list[Geometry]:
    r"""
    Normalize winding orders of contours (outer CCW, inner CW).
    """

def optimize_path_from_array(data: Optional[Sequence[Sequence[float]]], tolerance: float, fit_arcs: bool) -> Any:
    r"""
    Optimize a path by fitting arcs.
    """

def remove_duplicate_segments(data: Optional[Sequence[Sequence[float]]], tolerance: float = 0.000001) -> Any:
    r"""
    Remove duplicate segments from path data.
    """

def remove_duplicates(points: Sequence[tuple[float, float]]) -> list[tuple[float, float]]:
    r"""
    Remove duplicate points from a sequence.
    """

def remove_inner_edges(geometry: Geometry) -> Geometry:
    r"""
    Remove inner edges from a geometry.
    """

def reverse_contour(contour: Geometry) -> Geometry:
    r"""
    Reverse the direction of a contour.
    """

def split_inner_and_outer_contours(contours: list[Geometry]) -> tuple[list[Geometry], list[Geometry]]:
    r"""
    Split contours into inner and outer groups.
    """

def split_into_components(geometry: Geometry) -> list[Geometry]:
    r"""
    Split a geometry into connected components.
    """

def split_into_contours(geometry: Geometry) -> list[Geometry]:
    r"""
    Split a geometry into individual contours.
    """

