# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import numpy
import numpy.typing
from raygeo import Geometry
__all__ = [
    "parse_svg_path_data",
    "parse_svg_transform",
    "svg_string_to_geometries",
]

def parse_svg_path_data(path_data: str, transform: numpy.typing.NDArray[numpy.float64] | None = None, scale_x: float = 1, scale_y: float = 1) -> list[Geometry]:
    r"""
    Parse an SVG path d attribute into a list of Geometry objects.
    
    Supports M/m, L/l, H/h, V/v, C/c, Z/z commands.
    Cubic Bezier curves are flattened to line segments (20 steps).
    
    :param path_data: SVG path d attribute string.
    :param transform: 3x3 affine transformation matrix, or None for identity.
    :param scale_x: X-axis scale factor for coordinate transform.
    :param scale_y: Y-axis scale factor for coordinate transform.
    :returns: List of Geometry objects, one per subpath.
    """

def parse_svg_transform(transform_str: str) -> numpy.typing.NDArray[numpy.float64]:
    r"""
    Parse an SVG transform attribute string (translate only).
    
    Returns a 3x3 identity matrix with translation applied.
    
    :param transform_str: SVG transform attribute value.
    :returns: 3x3 affine transformation matrix as numpy array.
    """

def svg_string_to_geometries(svg_str: str, scale_x: float = 1, scale_y: float = 1) -> list[Geometry]:
    r"""
    Parse an SVG string and extract all path elements as Geometry objects.
    
    Recursively traverses the SVG XML tree, extracting d attributes
    from path elements and converting them to Geometry.
    
    :param svg_str: SVG document as a string.
    :param scale_x: X-axis scale factor for coordinate transform.
    :param scale_y: Y-axis scale factor for coordinate transform.
    :returns: List of Geometry objects from all path elements.
    """

