# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

__all__ = [
    "remove_duplicates",
]

def remove_duplicates(points: Sequence[Point]) -> Polygon:
    r"""
    Remove duplicate points from a sequence.
    
    :param points: Sequence of (x, y) points.
    :returns: List of unique points.
    """

