# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

__all__ = [
    "clip_line_segment_with_polygons",
    "clip_line_segment_with_rect",
    "subtract_polygons_from_line_segment",
]

def clip_line_segment_with_polygons(p1: tuple[float, float, float], p2: tuple[float, float, float], regions: Sequence[Sequence[tuple[float, float]]]) -> list[tuple[tuple[float, float, float], tuple[float, float, float]]]:
    r"""
    Clip line segments that fall within polygon regions.
    """

def clip_line_segment_with_rect(p1: tuple[float, float, float], p2: tuple[float, float, float], rect: tuple[float, float, float, float]) -> Optional[tuple[tuple[float, float, float], tuple[float, float, float]]]:
    r"""
    Clip a line segment with a rectangle.
    """

def subtract_polygons_from_line_segment(p1: tuple[float, float, float], p2: tuple[float, float, float], regions: Sequence[Sequence[tuple[float, float]]]) -> list[tuple[tuple[float, float, float], tuple[float, float, float]]]:
    r"""
    Subtract polygon regions from a line segment.
    """

