# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

__all__ = [
    "calculate_input_scale",
    "convolve_point_sequences",
    "convolve_two_segments",
    "get_inner_fit_polygon",
    "get_no_fit_polygon",
    "get_polygon_minkowski_sum_convex",
]

def calculate_input_scale(polygons: Sequence[Sequence[tuple[float, float]]], max_int: int = 2147483647) -> float:
    r"""
    Calculate the optimal input scale for clipper operations.
    """

def convolve_point_sequences(seq_a: Sequence[tuple[int, int]], seq_b: Sequence[tuple[int, int]]) -> list[list[tuple[int, int]]]:
    r"""
    Convolve two sequences of points.
    """

def convolve_two_segments(a1: tuple[int, int], a2: tuple[int, int], b1: tuple[int, int], b2: tuple[int, int]) -> list[tuple[int, int]]:
    r"""
    Convolve two line segments.
    """

def get_inner_fit_polygon(outer: Sequence[tuple[float, float]], inner: Sequence[tuple[float, float]]) -> list[list[tuple[float, float]]]:
    r"""
    Compute the inner fit polygon (no-fit polygon for nesting).
    """

def get_no_fit_polygon(subject: Sequence[tuple[float, float]], tool: Sequence[tuple[float, float]]) -> list[list[tuple[float, float]]]:
    r"""
    Compute the no-fit polygon for two 2D polygons.
    """

def get_polygon_minkowski_sum_convex(poly_a: Sequence[tuple[int, int]], poly_b: Sequence[tuple[int, int]]) -> list[list[tuple[int, int]]]:
    r"""
    Compute the Minkowski sum of two convex polygons.
    """

