# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Contour extraction from binary images.

Provides boundary tracing of foreground regions in a boolean image,
returning ordered point loops around each component in pixel
coordinates (y increases downward).
"""

import numpy
__all__ = [
    "find_external_contours",
]

def find_external_contours(boolean_image: numpy.ndarray) -> list[list[tuple[float, float]]]:
    r"""
    Trace the outer boundary of each foreground region.
    
    Pixels with value 0 are treated as background; non-zero values
    are foreground. Each contour is an ordered loop of (x, y) points
    in pixel coordinates; contours with fewer than 3 points are
    dropped.
    
    :param boolean_image: 2D boolean array.
    :returns: List of contours, each a list of (x, y) points.
    :complexity: O(w*h) time, O(w*h) space where w*h is the image size
    """

