# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
PDE-based spiral path tracing.

Given a triangle mesh with a Laplace solution (scalar field u),
traces a spiral path from the inner boundary (u=0) outward to the
outer boundary (u≈1) by following the piecewise-constant
vector field ∇u⊥ + α∇u.

Typical usage:
    from raygeo.geo.algo.pde_mesh import build_triangle_mesh, solve_laplace
    from raygeo.geo.algo.pde_spiral import trace_spiral
    mesh = build_triangle_mesh(outer, [hole])
    u = solve_laplace(mesh)
    path = trace_spiral(mesh, u, step_over=1.0)
"""

import collections.abc
from raygeo.geo.algo import pde_mesh
__all__ = [
    "trace_spiral",
]

def trace_spiral(mesh: pde_mesh.TriangleMesh, u_field: collections.abc.Sequence[float], step_over: float) -> list[tuple[float, float, float]]:
    r"""
    Trace a spiral toolpath from inner to outer boundary.
    
    Uses the piecewise-constant gradient of the scalar field u to
    trace a smooth spiral that morphs from the inner boundary (u=0)
    to the outer boundary (u=1) without self-intersections.
    
    :param mesh: TriangleMesh with boundary tags from build_triangle_mesh.
    :param u_field: Scalar field from solve_laplace, one value per vertex.
    :param step_over: Desired radial step-over distance between spiral
        turns. Larger values produce fewer, wider loops.
    :returns: List of (x, y, z) points forming the spiral polyline.
    :complexity: O(t * k) where t is the number of traversed triangles
    """

