# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import raygeo
import typing
__all__ = [
    "FrameSpec",
    "frame",
]

@typing.final
class FrameSpec:
    r"""
    Parameters for the ``frame`` assembler.
    
    Construct with ``FrameSpec(offset_mm, cut_side)``.
    Wrap in an :class:`~raygeo.ops.assembly.Assembler` instance to
    drive the `Assembler` trait.
    """
    @property
    def offset_mm(self) -> builtins.float:
        r"""
        Total path offset distance in mm.
        """
    @property
    def cut_side(self) -> builtins.str:
        r"""
        ``"centerline"``, ``"outside"``, or ``"inside"``.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, offset_mm: builtins.float = 0.0, cut_side: builtins.str = 'centerline') -> FrameSpec: ...

def frame(part: raygeo.ops.part.Part, offset_mm: float = 0, cut_side: str = 'centerline') -> raygeo.ops.assembly.AssemblyResult:
    r"""
    Generate a rectangular frame around the part boundary.
    
    Creates a rectangle matching ``part.size_mm``, computes the
    total offset from offset / cut-side, applies it, and returns
    the frame as an :class:`AssemblyResult`.
    
    :param part: The part whose size defines the frame.
    :param offset_mm: Total path offset distance in mm
        (default 0.0).
    :param cut_side: ``"centerline"``, ``"outside"``, or
        ``"inside"`` (default ``"centerline"``).
    :returns: An :class:`AssemblyResult` with the frame path.
    :raises ValueError: If the part has no size information.
    """

