# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "TriangleMesh",
]

@typing.final
class TriangleMesh:
    @property
    def vertices(self) -> builtins.list[tuple[builtins.float, builtins.float]]: ...
    @property
    def triangles(self) -> builtins.list[tuple[builtins.int, builtins.int, builtins.int]]: ...
    @property
    def adjacency(self) -> builtins.list[builtins.int]: ...
    @property
    def boundary_tags(self) -> builtins.list[builtins.str]: ...
    def __new__(cls) -> TriangleMesh: ...
    def __repr__(self) -> builtins.str: ...

