# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Medial Axis Transform (MAT) computation.

The MAT is the skeleton of a 2D domain — the set of points equidistant
to two or more boundary features.  It is computed via Delaunay-circumcenter
extraction from a constrained triangulation of the pocket boundary.

* ``compute_medial_axis`` — compute the MAT of a pocket (with optional islands).
"""

import collections.abc
__all__ = [
    "compute_medial_axis",
    "mat_path",
]

def compute_medial_axis(outer: collections.abc.Sequence[tuple[float, float]], holes: collections.abc.Sequence[collections.abc.Sequence[tuple[float, float]]] = [], tool_radius: float = 1, sampling_spacing: float = 1) -> tuple[list[tuple[float, float]], list[float], list[tuple[int, int]], int, list[list[int]]]:
    r"""
    Compute the Medial Axis Transform of a planar domain.
    
    Returns ``(nodes, clearances, edges, root, branches)``.
    
    :param outer: Outer boundary polygon (CCW).
    :param holes: List of hole polygons (CW). Defaults to [].
    :param tool_radius: Minimum clearance; narrower branches are pruned.
    :param sampling_spacing: Sampling density for boundary + Steiner grid.
                            Smaller = finer MAT.
    
    :returns:
        ``(nodes, clearances, edges, root, branches)`` where
    
        * **nodes** — ``list[(x, y)]`` of medial axis vertex positions.
        * **clearances** — ``list[float]`` inscribed circle radius per node.
        * **edges** — ``list[(int, int)]`` tree edges (parent, child).
        * **root** — ``int`` index of the maximum-clearance node.
        * **branches** — ``list[list[int]]`` each branch is a node-index path
          from a junction to another junction or leaf.
    """

def mat_path(outer: collections.abc.Sequence[tuple[float, float]], from_pt: tuple[float, float], to_pt: tuple[float, float], holes: collections.abc.Sequence[collections.abc.Sequence[tuple[float, float]]] = [], tool_radius: float = 1, sampling_spacing: float = 1) -> list[tuple[float, float]] | None:
    r"""
    Find a path between two points using the Medial Axis.
    
    Computes the MAT of the pocket defined by *outer* and *holes*,
    then finds the shortest-topology path between *from_pt* and
    *to_pt* along the medial axis graph.
    
    :param outer: Outer boundary polygon (CCW).
    :param from_pt: Start point (x, y).
    :param to_pt: End point (x, y).
    :param holes: List of hole polygons (CW). Defaults to [].
    :param tool_radius: Minimum clearance for MAT pruning.
    :param sampling_spacing: Boundary sampling density.
    :returns: List of (x, y) waypoints along the path, or None.
    """

