# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from raygeo import ops
import typing
__all__ = [
    "LinkStrategy",
    "link_passes",
    "polyline_to_ops",
]

@typing.final
class LinkStrategy:
    RETRACT: builtins.str = 'retract'
    STAY_DOWN: builtins.str = 'stay_down'

def link_passes(passes: list[ops.Ops], safe_z: float, strategy: str | LinkStrategy) -> ops.Ops:
    r"""
    Join ordered machining passes into a single Ops sequence.
    
    The first pass is emitted as-is; subsequent passes are prefixed
    with travel moves according to *strategy*:
    
    * ``"retract"`` / ``LinkStrategy.RETRACT`` — retract to
      *safe_z*, move XY at that height, then descend to the next
      pass start Z.
    * ``"stay_down"`` / ``LinkStrategy.STAY_DOWN`` — move directly
      from the previous pass end to the next pass start without
      retracting.
    
    :param passes: Ordered list of :class:`~raygeo.ops.Ops` passes.
    :param safe_z: Z height for retract moves (mm).
    :param strategy: Linking strategy.
    :returns: A single :class:`~raygeo.ops.Ops` container.
    """

def polyline_to_ops(points: list[tuple[float, float, float]], move_first: bool = True) -> ops.Ops:
    r"""
    Convert a 3-D polyline into an Ops command sequence.
    
    When *move_first* is ``True`` the first point is emitted as a
    MoveTo and subsequent points as LineTo.  When *move_first* is
    ``False`` every point is emitted as a LineTo (useful for
    appending a polyline to an in-progress cut).
    
    :param points: List of ``(x, y, z)`` tuples.
    :param move_first: Whether to emit the first point as a MoveTo.
    :returns: An :class:`~raygeo.ops.Ops` container.
    """

