# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Curve and primitive fitting algorithms.

Provides functions for fitting arcs, lines, circles, and beziers to
point sequences. Includes recursive fitting with primitives, polyline
linearization, and evaluating fitting quality (line and arc deviation).
"""

import collections.abc
from raygeo.geo import types
import typing
__all__ = [
    "are_points_collinear",
    "create_arc_cmd",
    "create_line_cmd",
    "fit_circle_to_3_points",
    "fit_circle_to_points",
    "fit_points_recursive",
    "fit_points_with_primitives",
    "flatten_to_points",
    "get_polyline_arc_deviation",
    "get_polyline_line_deviation",
    "linearize_geometry",
    "project_circle_center_to_bisector",
]

def are_points_collinear(points: collections.abc.Sequence[types.Point3D], tolerance: float = 0.000001) -> bool:
    r"""
    Check if three or more points are collinear within tolerance.
    
    :param points: Sequence of 3D points.
    :param tolerance: Collinearity tolerance.
    :returns: True if points are collinear.
    """

def create_arc_cmd(end: types.Point3D, center: types.Point, start: types.Point3D) -> list[float]:
    r"""
    Create an arc command array.
    
    :param end: End point (x, y, z).
    :param center: Center offset (dx, dy).
    :param start: Start point (x, y, z).
    :returns: Arc command array (8 floats).
    """

def create_line_cmd(end_point: types.Point3D) -> list[float]:
    r"""
    Create a line command array from an end point.
    
    :param end_point: End point (x, y, z).
    :returns: Line command array (8 floats).
    """

def fit_circle_to_3_points(p1: types.Point2DOr3D, p2: types.Point2DOr3D, p3: types.Point2DOr3D) -> typing.Optional[tuple[types.Point, float]]:
    r"""
    Fit a circle to three points.
    
    :param p1: First point (x, y) or (x, y, z).
    :param p2: Second point (x, y) or (x, y, z).
    :param p3: Third point (x, y) or (x, y, z).
    :returns: Tuple of (center, radius) or None.
    """

def fit_circle_to_points(points: collections.abc.Sequence[types.Point3D]) -> typing.Optional[tuple[types.Point, float, float]]:
    r"""
    Fit a circle to a set of points.
    
    :param points: Sequence of 3D points to fit.
    :returns: Tuple of (center, radius, error) or None.
    """

def fit_points_recursive(points: collections.abc.Sequence[types.Point3D], tolerance: float, start_idx: int, end_idx: int) -> list[list[float]]:
    r"""
    Recursively fit points with line and arc primitives.
    
    :param points: Sequence of 3D points to fit.
    :param tolerance: Fitting tolerance.
    :param start_idx: Start index in the points array.
    :param end_idx: End index in the points array.
    :returns: List of fitted command rows.
    """

def fit_points_with_primitives(points: collections.abc.Sequence[types.Point3D], tolerance: float) -> list[list[float]]:
    r"""
    Fit a polyline of points with arc and line primitives.
    
    :param points: Sequence of 3D points to fit.
    :param tolerance: Fitting tolerance.
    :returns: List of fitted command rows.
    """

def flatten_to_points(data: collections.abc.Sequence[collections.abc.Sequence[float]], tolerance: float) -> list[list[types.Point3D]]:
    r"""
    Flatten curves into linear segments.
    
    :param data: Array of command data.
    :param tolerance: Flattening tolerance.
    :returns: List of flattened point segments.
    """

def get_polyline_arc_deviation(points: collections.abc.Sequence[types.Point3D], center: types.Point, radius: float) -> float:
    r"""
    Get the maximum arc deviation for a set of points.
    
    :param points: Sequence of 3D points.
    :param center: Arc center (x, y).
    :param radius: Arc radius.
    :returns: Maximum deviation from the arc.
    """

def get_polyline_line_deviation(points: collections.abc.Sequence[types.Point3D], start: int, end: int) -> tuple[float, int]:
    r"""
    Get the maximum line deviation for a segment of a polyline.
    
    :param points: Sequence of 3D points.
    :param start: Start index.
    :param end: End index.
    :returns: Tuple of (max_deviation, index_of_max).
    """

def linearize_geometry(data: collections.abc.Sequence[collections.abc.Sequence[float]], tolerance: float) -> list[list[float]]:
    r"""
    Linearize geometry data into line segments.
    
    :param data: Array of command data.
    :param tolerance: Linearization tolerance.
    :returns: List of linearized segment rows.
    """

def project_circle_center_to_bisector(p1: types.Point2DOr3D, p2: types.Point2DOr3D, center: types.Point) -> types.Point:
    r"""
    Project a circle center onto the perpendicular bisector of two points.
    
    :param p1: First point (x, y) or (x, y, z).
    :param p2: Second point (x, y) or (x, y, z).
    :param center: Circle center to project.
    :returns: Projected center point (x, y).
    """

