# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Curve and primitive fitting algorithms.

Provides functions for fitting arcs, lines, circles, and beziers to
point sequences. Includes recursive fitting with primitives, polyline
linearization, and evaluating fitting quality (line and arc deviation).
"""

import collections.abc
from raygeo import geo
from raygeo.geo import types
import typing
__all__ = [
    "are_points_collinear",
    "fit_circle_to_3_points",
    "fit_circle_to_points",
    "fit_points_recursive",
    "fit_points_with_primitives",
    "flatten_to_points",
    "generate_arc_between_two_points",
    "generate_linking_arc",
    "get_polyline_arc_deviation",
    "get_polyline_line_deviation",
    "linearize_geometry",
    "project_circle_center_to_bisector",
]

def are_points_collinear(points: collections.abc.Sequence[types.Point3D], tolerance: float = 0.000001) -> bool:
    r"""
    Check if three or more points are collinear within tolerance.
    
    :param points: Sequence of 3D points.
    :param tolerance: Collinearity tolerance.
    :returns: True if points are collinear.
    :complexity: O(n) time, O(1) space
    """

def fit_circle_to_3_points(p1: types.Point2DOr3D, p2: types.Point2DOr3D, p3: types.Point2DOr3D) -> typing.Optional[tuple[types.Point, float]]:
    r"""
    Fit a circle to three points.
    
    :param p1: First point (x, y) or (x, y, z).
    :param p2: Second point (x, y) or (x, y, z).
    :param p3: Third point (x, y) or (x, y, z).
    :returns: Tuple of (center, radius) or None.
    :complexity: O(1) time, O(1) space
    """

def fit_circle_to_points(points: collections.abc.Sequence[types.Point3D]) -> typing.Optional[tuple[types.Point, float, float]]:
    r"""
    Fit a circle to a set of points.
    
    :param points: Sequence of 3D points to fit.
    :returns: Tuple of (center, radius, error) or None.
    :complexity: O(n) time, O(1) space
    """

def fit_points_recursive(points: collections.abc.Sequence[types.Point3D], tolerance: float, start_idx: int, end_idx: int) -> geo.Geometry:
    r"""
    Recursively fit points with line and arc primitives.
    
    :param points: Sequence of 3D points to fit.
    :param tolerance: Fitting tolerance.
    :param start_idx: Start index in the points array.
    :param end_idx: End index in the points array.
    :returns: Geometry of fitted commands.
    :complexity: O(n log n) average time, O(n) space
    """

def fit_points_with_primitives(points: collections.abc.Sequence[types.Point3D], tolerance: float) -> geo.Geometry:
    r"""
    Fit a polyline of points with arc and line primitives.
    
    :param points: Sequence of 3D points to fit.
    :param tolerance: Fitting tolerance.
    :returns: Geometry of fitted commands.
    :complexity: O(n log n) average time, O(n) space
    """

def flatten_to_points(geometry: geo.Geometry, tolerance: float) -> list[list[types.Point3D]]:
    r"""
    Flatten curves into linear segments.
    
    :param geometry: Geometry to flatten.
    :param tolerance: Flattening tolerance.
    :returns: List of flattened point segments.
    :complexity: O(n + m) time, O(m) space where n is the number of commands and m the number of output points
    """

def generate_arc_between_two_points(p0: tuple[float, float], p1: tuple[float, float], offset: float, min_radius: float, z: float, resolution: float) -> typing.Optional[list[tuple[float, float, float]]]:
    r"""
    Fit a circular arc through two points with a perpendicular offset.
    
    Uses a third point offset perpendicularly from the chord midpoint to
    define the arc shape.  Returns a linearized arc polyline, or None if
    the radius would be below min_radius or the geometry is degenerate.
    
    :param p0: Start point (x, y).
    :param p1: End point (x, y).
    :param offset: Perpendicular offset from the chord midpoint.
    :param min_radius: Minimum allowed arc radius.
    :param z: Z-coordinate for all output points.
    :param resolution: Arc linearization resolution.
    :returns: List of 3D points forming the arc, or None.
    :complexity: O(n) time, O(n) space where n depends on arc length and resolution
    """

def generate_linking_arc(start: tuple[float, float, float], end: tuple[float, float, float], min_radius: float, z: float) -> list[tuple[float, float, float]]:
    r"""
    Generate a smooth linking arc between two points.
    
    Uses generate_arc_between_two_points internally with an offset derived from
    min_radius.  Falls back to a straight-line interpolation if no valid
    arc can be fit.
    
    :param start: Start 3D point (x, y, z).
    :param end: End 3D point (x, y, z).
    :param min_radius: Minimum allowed arc radius.
    :param z: Z-coordinate for all output points (overrides start.z / end.z).
    :returns: List of 3D points forming the linking arc.
    :complexity: O(n) time, O(n) space where n scales with chord_length / min_radius
    """

def get_polyline_arc_deviation(points: collections.abc.Sequence[types.Point3D], center: types.Point, radius: float) -> float:
    r"""
    Get the maximum arc deviation for a set of points.
    
    :param points: Sequence of 3D points.
    :param center: Arc center (x, y).
    :param radius: Arc radius.
    :returns: Maximum deviation from the arc.
    :complexity: O(n) time, O(1) space
    """

def get_polyline_line_deviation(points: collections.abc.Sequence[types.Point3D], start: int, end: int) -> tuple[float, int]:
    r"""
    Get the maximum line deviation for a segment of a polyline.
    
    :param points: Sequence of 3D points.
    :param start: Start index.
    :param end: End index.
    :returns: Tuple of (max_deviation, index_of_max).
    :complexity: O(n) time, O(1) space
    """

def linearize_geometry(geometry: geo.Geometry, tolerance: float) -> geo.Geometry:
    r"""
    Linearize geometry data into line segments.
    
    :param geometry: Geometry to linearize.
    :param tolerance: Linearization tolerance.
    :returns: Linearized Geometry.
    :complexity: O(n + m) time, O(m) space where n is the number of commands and m the number of output segments
    """

def project_circle_center_to_bisector(p1: types.Point2DOr3D, p2: types.Point2DOr3D, center: types.Point) -> types.Point:
    r"""
    Project a circle center onto the perpendicular bisector of two points.
    
    :param p1: First point (x, y) or (x, y, z).
    :param p2: Second point (x, y) or (x, y, z).
    :param center: Circle center to project.
    :returns: Projected center point (x, y).
    :complexity: O(1) time, O(1) space
    """

