# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Individual point operations.

Provides equality testing within a configurable tolerance, midpoint
computation between two points, and applying a 4x4 affine transformation
matrix to a single point.
"""

__all__ = [
    "are_points_equal",
    "midpoint",
    "transform_point",
]

def are_points_equal(p1: Point3D, p2: Point3D, tolerance: float) -> bool:
    r"""
    Check if two 3D points are equal within tolerance.
    
    :param p1: First point (x, y, z).
    :param p2: Second point (x, y, z).
    :param tolerance: Maximum allowed difference.
    :returns: True if points are equal within tolerance.
    """

def midpoint(p1: Point3D, p2: Point3D) -> Point3D:
    r"""
    Get the midpoint between two 3D points.
    
    :param p1: First point (x, y, z).
    :param p2: Second point (x, y, z).
    :returns: Midpoint (x, y, z).
    """

def transform_point(matrix: Sequence[Sequence[float]], x: float, y: float, z: float) -> Point3D:
    r"""
    Apply an affine transformation matrix to a 3D point.
    
    :param matrix: 4x4 affine transformation matrix.
    :param x: X coordinate.
    :param y: Y coordinate.
    :param z: Z coordinate.
    :returns: Transformed point (x, y, z).
    """

