# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Arc geometry queries and conversions.

Provides bounding rectangle computation, intersection tests (arc-rect,
arc-circle, arc-polygons), arc linearization into line segments for
rendering or further processing, angle utilities (normalize, direction,
containment), and arc midpoint / closest-point lookups.
"""

import collections.abc
from raygeo.geo import types
import typing
__all__ = [
    "does_arc_intersect_circle",
    "does_arc_intersect_rect",
    "get_arc_angles",
    "get_arc_bounds",
    "get_arc_closest_point",
    "get_arc_direction",
    "get_arc_length",
    "get_arc_midpoint",
    "is_angle_between",
    "is_arc_clockwise",
    "is_arc_inside_polygons",
    "linearize_arc",
    "normalize_angle",
]

def does_arc_intersect_circle(arc_start: types.Point, arc_end: types.Point, arc_center: types.Point, clockwise: bool, circle_center: types.Point, circle_radius: float) -> bool:
    r"""
    Check if an arc intersects a circle.
    
    :param arc_start: Arc start point (x, y).
    :param arc_end: Arc end point (x, y).
    :param arc_center: Arc center point (x, y).
    :param clockwise: Whether the arc is clockwise.
    :param circle_center: Circle center (x, y).
    :param circle_radius: Circle radius.
    :returns: True if the arc intersects the circle.
    """

def does_arc_intersect_rect(arc_start: types.Point, arc_end: types.Point, arc_center: types.Point, clockwise: bool, rect: types.Rect) -> bool:
    r"""
    Check if an arc intersects a rectangle.
    
    :param arc_start: Arc start point (x, y).
    :param arc_end: Arc end point (x, y).
    :param arc_center: Arc center point (x, y).
    :param clockwise: Whether the arc is clockwise.
    :param rect: Rectangle (x_min, y_min, x_max, y_max).
    :returns: True if the arc intersects the rectangle.
    """

def get_arc_angles(start: types.Point, end: types.Point, center: types.Point, clockwise: bool) -> types.Point3D:
    r"""
    Get the start, end, and sweep angles of an arc.
    
    :param start: Arc start point (x, y).
    :param end: Arc end point (x, y).
    :param center: Arc center point (x, y).
    :param clockwise: Whether the arc is clockwise.
    :returns: Tuple of (start_angle, end_angle, sweep_angle) in radians.
    """

def get_arc_bounds(start: types.Point, end: types.Point, center: types.Point, clockwise: bool) -> types.Rect:
    r"""
    Get the bounding rectangle of an arc.
    
    :param start: Arc start point (x, y).
    :param end: Arc end point (x, y).
    :param center: Arc center point (x, y).
    :param clockwise: Whether the arc is clockwise.
    :returns: Bounding rectangle as (x_min, y_min, x_max, y_max).
    """

def get_arc_closest_point(arc_cmd: typing.Any, start_pos: types.Point3D, x: float, y: float) -> typing.Optional[tuple[float, types.Point, float]]:
    r"""
    Get the closest point on an arc to a given point.
    
    :param arc_cmd: Arc command row or MockArc-like object.
    :param start_pos: Start position (x, y, z).
    :param x: X coordinate of target point.
    :param y: Y coordinate of target point.
    :returns: Tuple of (parameter, closest_point, distance) or None.
    """

def get_arc_direction(center: types.Point, start: types.Point, mouse: types.Point) -> bool:
    r"""
    Get the direction (CW/CCW) of an arc at a mouse point.
    
    :param center: Arc center (x, y).
    :param start: Arc start point (x, y).
    :param mouse: Mouse point (x, y).
    :returns: True if clockwise, False if counter-clockwise.
    """

def get_arc_length(start_pos: types.Point, end_pos: types.Point, center_offset: types.Point, clockwise: bool) -> float:
    r"""
    Compute the arc length of a circular arc.
    
    :param start_pos: Start point (x, y).
    :param end_pos: End point (x, y).
    :param center_offset: Center offset (i, j) from start.
    :param clockwise: True for clockwise, False for counter-clockwise.
    :returns: Arc length.
    """

def get_arc_midpoint(start: types.Point, end: types.Point, center: types.Point, clockwise: bool) -> types.Point:
    r"""
    Get the midpoint of an arc.
    
    :param start: Arc start point (x, y).
    :param end: Arc end point (x, y).
    :param center: Arc center point (x, y).
    :param clockwise: Whether the arc is clockwise.
    :returns: Midpoint (x, y).
    """

def is_angle_between(angle: float, start: float, end: float, clockwise: bool) -> bool:
    r"""
    Check if an angle is between two other angles.
    
    :param angle: Angle to test.
    :param start: Start angle.
    :param end: End angle.
    :param clockwise: Whether the arc is clockwise.
    :returns: True if angle is between start and end.
    """

def is_arc_clockwise(points: collections.abc.Sequence[types.Point2DOr3D], center: types.Point2DOr3D) -> bool:
    r"""
    Check if an arc is clockwise.
    
    :param points: Sequence of (x, y) points on the arc.
    :param center: Arc center (x, y).
    :returns: True if the arc is clockwise.
    """

def is_arc_inside_polygons(arc_start: types.Point, arc_end: types.Point, arc_center: types.Point, clockwise: bool, polygons: typing.Any) -> bool:
    r"""
    Check if an arc is inside a set of polygons.
    
    :param arc_start: Arc start point (x, y).
    :param arc_end: Arc end point (x, y).
    :param arc_center: Arc center point (x, y).
    :param clockwise: Whether the arc is clockwise.
    :param polygons: List of polygons to check against.
    :returns: True if the arc is inside all polygons.
    """

def linearize_arc(arc_cmd: typing.Any, start_point: types.Point3D, resolution: float = 0.1) -> list[tuple[types.Point3D, types.Point3D]]:
    r"""
    Linearize an arc into line segments.
    
    :param arc_cmd: Arc command row or MockArc-like object.
    :param start_point: Start point (x, y, z).
    :param resolution: Maximum segment length.
    :returns: List of (p1, p2) segment pairs.
    """

def normalize_angle(angle: float) -> float:
    r"""
    Normalize an angle to the range [0, 2*pi).
    
    :param angle: Angle in radians.
    :returns: Normalized angle in [0, 2*pi).
    """

