# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
CNC tool model.

Provides ToolModel (a parametric geometry parameter bag), the
ToolCategory enum (type-safe tool classification for compatibility
checks), the ToolMaterial enum, and the Tool composite. All types are
implemented in Rust and consumed by the CNC layer's signatures.
"""

import builtins
import enum
import typing
__all__ = [
    "Tool",
    "ToolCategory",
    "ToolMaterial",
    "ToolModel",
]

@typing.final
class Tool:
    r"""
    A physical cutting tool.
    
    Combines a parametric :class:`ToolModel` (measurements), a
    :class:`ToolCategory` (type-safe classification), a
    :class:`ToolMaterial`, and setup parameters:
    
    .. code-block:: python
    
       tool = Tool(
           label="6mm EM",
           category=ToolCategory.EndMill,
           model=ToolModel(diameter=6.0, ...),
           material=ToolMaterial.Carbide,
           stickout=15.0,
       )
    """
    @property
    def label(self) -> builtins.str: ...
    @property
    def category(self) -> ToolCategory: ...
    @property
    def material(self) -> ToolMaterial: ...
    @property
    def stickout(self) -> builtins.float: ...
    @property
    def coating(self) -> typing.Optional[builtins.str]: ...
    @property
    def model(self) -> ToolModel:
        r"""
        The tool's parametric geometry model.
        """
    def __new__(cls, label: builtins.str, category: ToolCategory, model: ToolModel, material: ToolMaterial, stickout: builtins.float, coating: typing.Optional[builtins.str] = None) -> Tool: ...
    def __repr__(self) -> builtins.str: ...
    def diameter(self) -> builtins.float:
        r"""
        Cutting diameter (mm).
        """
    def default_stickout(self) -> builtins.float:
        r"""
        Default stickout = cutting edge height + 3 mm safety.
        """

@typing.final
class ToolModel:
    r"""
    Parametric model describing a tool's geometry.
    
    A single, hierarchy-free class: a bag of named parameters. Construct
    with keyword arguments for each parameter:
    
    .. code-block:: python
    
       model = ToolModel(
           diameter=6.0,
           shank_diameter=6.0,
           cutting_edge_height=15.0,
           flute_count=3.0,
           overall_length=50.0,
       )
    
    The type-safe tool *classification* (end-mill vs. probe vs. ...) lives
    on :class:`Tool` as the :class:`ToolCategory` enum; a ``ToolModel``
    only carries measurements. New geometries are created by constructing
    a ``ToolModel`` with new parameters -- no raygeo change required.
    """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, **kwargs: typing.Any) -> ToolModel: ...
    def __repr__(self) -> builtins.str: ...
    def get_parameter(self, name: builtins.str) -> typing.Optional[builtins.float]:
        r"""
        Read a named parameter, or ``None`` if absent.
        """
    def get_parameters(self) -> builtins.dict[builtins.str, builtins.float]:
        r"""
        All parameters as a ``{name: value}`` dict.
        """
    def diameter(self) -> builtins.float:
        r"""
        Cutting diameter (mm); ``0.0`` if unspecified.
        """
    def corner_radius(self) -> builtins.float:
        r"""
        Corner radius (mm); ``0.0`` if unspecified.
        """
    def cutting_edge_height(self) -> builtins.float:
        r"""
        Cutting-edge height (mm); ``0.0`` if unspecified.
        """

@typing.final
class ToolCategory(enum.Enum):
    r"""
    Type-safe classification of a tool, for operation-compatibility
    checks (e.g. chamfering requires ``Chamfer``/``Vbit``, slotting
    rejects ``Probe``).
    """
    EndMill = ...
    BallNose = ...
    BullNose = ...
    Chamfer = ...
    Drill = ...
    Probe = ...
    Vbit = ...
    SlittingSaw = ...
    Reamer = ...
    Tap = ...
    ThreadMill = ...
    Dovetail = ...

@typing.final
class ToolMaterial(enum.Enum):
    r"""
    Tool substrate material.
    """
    Carbide = ...
    HSS = ...
    HSSE = ...
    Diamond = ...
    CBN = ...
    Ceramic = ...

