# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
CNC clearing plan builder.

Produces a :class:`~raygeo.cnc.plan.Plan` organised as a BFS traversal
of the pocket's region/passage graph.
"""

import builtins
from raygeo.cnc import plan
from raygeo.ops import part
__all__ = [
    "plan_clearing",
]

def plan_clearing(part: part.Part, face_id: builtins.str = '', tool_radius: builtins.float = 3.0, step_over: builtins.float = 2.0, step_length: builtins.float = 0.6, target_z: builtins.float = -5.0, safe_z: builtins.float = 2.0, wall_margin: builtins.float = 0.0, safe_margin: builtins.float = 1.0, stock_to_leave: builtins.float = 0.0, plunge_pitch: builtins.float = 1.0, angular_step: builtins.float = 0.1, area_tolerance: builtins.float = 1.0, max_deflection_deg: builtins.float = 30.0, finishing: builtins.bool = False) -> plan.Plan: ...

