# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Polyline simplification using the Ramer-Douglas-Peucker algorithm.

Reduces the number of points in a polyline while preserving the overall
shape within a given tolerance.
"""

import collections.abc
from raygeo import geo
__all__ = [
    "simplify_polyline",
]

def simplify_polyline(points: collections.abc.Sequence[types.Point], tolerance: float) -> types.Polygon:
    r"""
    Simplify a polyline using the Ramer-Douglas-Peucker algorithm.
    
    :param points: Sequence of (x, y) points.
    :param tolerance: Simplification tolerance.
    :returns: Simplified point sequence.
    """

