# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Circle-boundary overlap (engagement) metrics.
"""

__all__ = [
    "angular_engagement",
    "compute_engagement",
    "point_engagement",
]

def angular_engagement(center: tuple[float, float], radius: float, fragments: list[list[tuple[float, float]]]) -> float:
    r"""
    Angular engagement (exact circle–polygon intersection).
    
    Returns uncleared angular extent in ``[0, 2π]``.
    
    :param center: Disk centre ``(x, y)``.
    :param radius: Disk radius (mm).
    :param fragments: List of polygons (cleared fragments).
    :returns: Angular engagement in radians.
    """

def compute_engagement(d_to_boundary: float, radius: float) -> tuple[float, float, float]:
    r"""
    Compute engagement angle, area, and chord depth.
    
    :param d_to_boundary: Signed distance from the point to the nearest boundary
        (mm).  Positive = outside the boundary.
    :param radius: Disk radius (mm).
    :returns: ``(angle_rad, area, chord_depth)``.
    """

def point_engagement(center: tuple[float, float], radius: float, fragments: list[list[tuple[float, float]]]) -> tuple[float, float, float]:
    r"""
    Engagement angle, area, and chord depth at a disk centre.
    
    :param center: Disk centre ``(x, y)``.
    :param radius: Disk radius (mm).
    :param fragments: List of polygons (cleared fragments).
    :returns: ``(angle_rad, area, chord_depth)``.
    """

