r"""Machine state tracking for laser cutting.

Tracks the current or intended machine state at any point in a command
sequence, including power level (0.0–1.0), air assist on/off, cut speed
and travel speed, active laser source UID, pulse frequency, and pulse
width. State objects are used by Ops to associate machine parameters
with moving commands and to detect rapid (non-power) state changes.
"""

# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "State",
]

@typing.final
class State:
    r"""
    The current state of a laser cutting job.
    
    Tracks power level, air assist, cut/travel speeds,
    active laser UID, frequency, and pulse width.
    """
    @property
    def power(self) -> builtins.float:
        r"""
        Laser power level (0.0 – 1.0 typically).
        """
    @power.setter
    def power(self, value: builtins.float) -> None: ...
    @property
    def air_assist(self) -> builtins.bool:
        r"""
        Whether air assist is enabled.
        """
    @air_assist.setter
    def air_assist(self, value: builtins.bool) -> None: ...
    @property
    def cut_speed(self) -> typing.Optional[builtins.int]:
        r"""
        Cutting speed in mm/s (if set).
        """
    @cut_speed.setter
    def cut_speed(self, value: typing.Optional[builtins.int]) -> None: ...
    @property
    def travel_speed(self) -> typing.Optional[builtins.int]:
        r"""
        Travel (rapid) speed in mm/s (if set).
        """
    @travel_speed.setter
    def travel_speed(self, value: typing.Optional[builtins.int]) -> None: ...
    @property
    def active_laser_uid(self) -> typing.Optional[builtins.str]:
        r"""
        UID of the active laser source (if set).
        """
    @active_laser_uid.setter
    def active_laser_uid(self, value: typing.Optional[builtins.str]) -> None: ...
    @property
    def frequency(self) -> typing.Optional[builtins.int]:
        r"""
        Laser pulse frequency in Hz (if set).
        """
    @frequency.setter
    def frequency(self, value: typing.Optional[builtins.int]) -> None: ...
    @property
    def pulse_width(self) -> typing.Optional[builtins.float]:
        r"""
        Laser pulse width in microseconds (if set).
        """
    @pulse_width.setter
    def pulse_width(self, value: typing.Optional[builtins.float]) -> None: ...
    def __new__(cls, power: builtins.float = 0.0, air_assist: builtins.bool = False, cut_speed: typing.Optional[builtins.int] = None, travel_speed: typing.Optional[builtins.int] = None, active_laser_uid: typing.Optional[builtins.str] = None, frequency: typing.Optional[builtins.int] = None, pulse_width: typing.Optional[builtins.float] = None) -> State: ...
    def __repr__(self) -> builtins.str:
        r"""
        String representation like ``State(power=..., air_assist=...)``.
        """
    def allow_rapid_change(self, target: State) -> builtins.bool:
        r"""
        Check whether the machine can transition from the current
        state to the *target* state without a ``SetPower`` command.
        
        :param target: The target state to compare against.
        :returns: True if the change is a rapid (non-power) change.
        """

