# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
Adaptive stepping solver and resume-point search for material removal.

Provides the forward-stepping engagement solver, angle interpolation,
and frontier-walk search used by the adaptive clearing assembler.
"""

from . import interp
from . import search
from . import stepper
__all__ = [
    "interp",
    "search",
    "stepper",
]

