# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "CacheKey",
]

@typing.final
class CacheKey:
    @property
    def tag(self) -> builtins.str: ...
    @property
    def payload_hash(self) -> builtins.int: ...
    def __new__(cls, tag: builtins.str, payload_hash: builtins.int) -> CacheKey: ...
    def __repr__(self) -> builtins.str: ...

