# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "MultiPassSpec",
]

@typing.final
class MultiPassSpec:
    r"""
    Parameters for the ``MultiPass`` transformer.
    """
    @property
    def passes(self) -> builtins.int:
        r"""
        Total number of passes (must be >= 1).
        """
    @property
    def z_step_down(self) -> builtins.float:
        r"""
        Z distance to move down after each pass.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, passes: builtins.int, z_step_down: builtins.float) -> MultiPassSpec: ...

